{if !empty($tasks)}
	<table id="task-stats" cellspacing="0">
		<thead>
			<th>#</th>
			<th>{_'název'}</th>
			<th>{_'nejhorší'}</th>
			<th>{_'nejlepší'}</th>
			{*<th>průměrný</th>*}
			<th>{_'správně'}</th>
			<th>{_'špatně'}</th>
                        <th>{_'přeskočeno'}</th>
		</thead>
		{foreach $tasks AS $task}
			<tr{if $iterator->isEven()} class="even"{/if}>
				<td>{$task->code_name}</td>
				<td>{$task|i18n:'name',$control->getPresenter()->lang}</td>
				<td>{$task->worst_time|timeOnly}</td>
				<td>{$task->best_time|timeOnly}</td>
				{*<td>{$task->avg_time|timeOnly}</td>*}
				<td>{$task->count_correct_answer}</td>
				<td>{$task->count_incorrect_answer}</td>
                                <td>{$task->count_skipped}</td>
			</tr>
		{/foreach}
	</table>
{/if}