<table class="table table-condensed table-striped">
    <thead>
    <th>#</th>
    <th>{_'úkol'}</th>
    <th>{_'vloženo'}</th>
    <th>{_'odpověď'}</th>
</thead>
	{foreach $history AS $answer}
<tr{if isset($correct[$answer->id_answer])} class="bg-success"{else} class="bg-danger"{/if}>
    <td>{$answer->id_answer}</td>
    <td>{$tasks[$answer->id_task]->code_name}</td>
    <td>{$answer->inserted|timeOnly}</td>
    <td>{if $tasks[$answer->id_task]->answer_type == TasksModel::TYPE_STR}
                    {$answer->answer_str}
                    {elseif $tasks[$answer->id_task]->answer_type == TasksModel::TYPE_INT}
                    {$answer->answer_int}
                    {elseif $tasks[$answer->id_task]->answer_type == TasksModel::TYPE_REAL}
                    {$answer->answer_real}
                    {/if}
    </td>
</tr>
	{/foreach}
</table>

{widget paginator}