<div id="teams" class="list">
    {foreach $categories AS $category => $categoryName}
        {if isset($teams[$category])}
	<h2 id="{$category}">{$categoryName}</h2>
	<ol>
	    {foreach $teams[$category] AS $team}
		<li>
			<strong>{$team->name}</strong>:
				{if isset($competitors[$team->id_team])}
					{foreach $competitors[$team->id_team] AS $competitor}
						{$competitor->name} {if $competitor->school_name != NULL}({$competitor->school_name}){/if}{if !$iterator->isLast()}, {/if}
					{/foreach}
				{else}
				{_'informace o členech týmu nejsou dostupné'}
				{/if}
		</li>
	    {/foreach}
	</ol>
        {/if}
    {/foreach}
</div>
