{widget flashMessages}
{if $valid}
<script type="text/javascript" src="{$baseUri}js/taskInfo.js"></script>
{widget form}

<script type="text/javascript">
    $('#'+{$tasksInfoElement}).infoElement($('#'+{$control['form']['task']->getHtmlId()}), {'data': {$tasksInfo}, 'realHint': {$realHint}, 'expected': {$expected}, 'unit': {$unit}});    
    $(function(){
        var timesecs = $('.timesec');
        var button = $('#'+{$control['form'][$submitElement]->getHtmlId()});
        if(timesecs.length){
            button.attr('disabled', 'disabled');
        }
        timesecs.timeElement({'handler': function(){
                button.removeAttr('disabled');
        }});
    });
</script>

{/if}