<?xml version="1.0" encoding="utf-8" ?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs">
    <head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta http-equiv="content-language" content="cs" />
		<link rel="stylesheet" type="text/css" href="{$baseUri}css/main.css" />
		<link rel="stylesheet" type="text/css" href="{$baseUri}css/forms.css" />
		<link rel="stylesheet" type="text/css" href="{$baseUri}css/flashes.css" />
		<link href="{$baseUri}favicon.png" rel="icon" type="image/png" />
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
                <script type="text/javascript" src="http://code.jquery.com/ui/1.8.2/jquery-ui.js"></script>

		<title>
	    {_'Fyziklání online'}{ifset $pageTite} - {$pageTitle}{/ifset}
		</title>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-27814405-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript';
ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' :
'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(ga, s);
  })();
</script>
    </head>

    <body>
		{block body}
		<!-- HEADER -->
		<div id="header">
			<a href="{link Default:default}" title="{_'Fyziklání online'}">
				<div class="wrapper">
					<div id="logo"></div>
					<h1>{_ 'Fyziklání online'}</h1>
				</div>
			</a>
		</div>
		<!-- MENU -->
		<div id="menu">
			<div class="wrapper">
				{if Interlos::isGameActive()}
					{widget clock}
				{/if}
				<ul id="team-navigation">
			{if Interlos::isRegistrationActive()}
			    {if !Environment::getUser()->isLoggedIn()}
					<li><a href="{link Team:registration}">{_ 'Registrace'}</a></li>
			    {/if}
			{/if}
			{if Interlos::isRegistrationStarted()}
			    {if !Environment::getUser()->isLoggedIn()}
					<li><a href="{link Default:login}">{_'Přihlásit se'}</a></li>
			    {else}
					<li><a href="{link Default:logout}" title="{_'Odhlásit se'}">{_'Odhlásit se'}</a></li>
					<li><a href="{link Team:default}" title="{=Interlos::getLoggedTeam()->name}">{=String::truncate(Interlos::getLoggedTeam()->name, 15)}</a></li>
			    {/if}
			{/if}
                                    <li n:if="$control->lang == 'cs'"><a href="{link this, lang => 'en'}"><img src="{$baseUri}images/icons/us-icon.png" alt="English" title="Switch to English"/></a></li>
                                    <li n:if="$control->lang == 'en'"><a href="{link this, lang => 'cs'}"><img src="{$baseUri}images/icons/cz-icon.png" alt="čeština" title="Přepnout do češtiny"/></a></li>                                    
				</ul>
				<ul id="general-navigation">
					<li><a href="{link Default:rules}" title="{_'Pravidla'}">{_'Pravidla'}</a></li>
					<li><a href="{link Default:lastYears}" title="{_'Minulé ročníky'}">{_'Minulé ročníky'}</a></li>
					{*<li><a href="{link Default:taskExamples}" title="{_'Rozcvička'}">{_'Rozcvička'}</a></li>*}
				{if Interlos::isRegistrationStarted()}
					<li><a href="{link Default:chat}" title="{_'Diskuse'}">{_'Diskuse'}</a></li>
					<li><a href="{link Team:list}" title="{_'Týmy'}">{_'Týmy'}</a></li>
			    {if Interlos::isGameStarted()}
					{if Environment::getUser()->isLoggedIn()}
						<li {if Interlos::isGameActive()}class="highlight"{/if}><a href="{link Game:default}" title="{_'Hra'}">{_'Hra'}</a></li>
					{/if}
					<li><a href="{link Stats:default}" title="{_'Statistiky'}">{_'Statistiky'}</a></li>
			    {/if}
			{/if}
				</ul>
			</div>
		</div>
		<div class="wrapper">
			<!-- PAGE TITLE -->
			<h1 n:ifset="$pageTitle">{$pageTitle}</h1>
			<!-- FLASH MESSAGES -->
            {widget flashMessages}
			<!-- CONTENT -->
			<div id="content">
		    {block #content}{/block}
			</div>
		</div>
		<div id="footer"></div>
                {/block}
    </body>
</html>
