<!DOCTYPE html>
<html lang="{$presenter->lang}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link href="{$baseUri}favicon.png" rel="icon" type="image/png" />

        <title>{_'Fyziklání online'}{ifset $pageTitle} &ndash; {$pageTitle}{/ifset}</title>

        <!-- Bootstrap core CSS -->
        <!--<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">-->
        <link href="{$baseUri}css/bootstrap.min.css" rel="stylesheet">
        <link href="{$baseUri}css/bootstrap-theme.min.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body onload="fixNavbarIssue()">
        {block body}
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">{_'Zobrazit navigaci'}</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{link Default:default}">{_'Fyziklání online'}</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{link Default:rules}" title="{_'Pravidla'}">{_'Pravidla'}</a></li>
                        <li><a href="{link Default:lastYears}" title="{_'Minulé ročníky'}">{_'Minulé ročníky'}</a></li>
                        {if Interlos::isRegistrationStarted()}
                        <li><a href="{link Default:chat}" title="{_'Diskuse'}">{_'Diskuse'}</a></li>
                        <li><a href="{link Team:list}" title="{_'Týmy'}">
                                <span class="hidden-sm">{_'Týmy'}</span>
                                <span class="visible-sm-inline glyphicon glyphicon-list"/>                                
                            </a></li>
                        {if Interlos::isGameStarted()}
                        <li><a href="{link Stats:default}" title="{_'Statistiky'}">
                                <span class="hidden-sm">{_'Statistiky'}</span>
                                <span class="visible-sm-inline glyphicon glyphicon-stats"/>
                            </a></li>
                        {if Environment::getUser()->isLoggedIn()}
                        <li {if Interlos::isGameActive()}class="active"{/if}><a href="{link Game:default}" title="{_'Hra'}">
                                <span class="hidden-sm">{_'Hra'}</span>
                                <span class="visible-sm-inline glyphicon glyphicon-globe"/>
                            </a></li>
                        {/if}
                        {/if}
                        {/if}
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {if Interlos::isRegistrationActive()}
                        {if !Environment::getUser()->isLoggedIn()}
                        <li><a href="{link Team:registration}">
                                <span class="hidden-sm">{_ 'Registrace'}</span>
                                <span class="visible-sm-inline glyphicon glyphicon-edit" title="{_'Registrace'}"/>
                            </a></li>
                        {/if}
                        {/if}
                        {if Interlos::isRegistrationStarted()}
                        {if !Environment::getUser()->isLoggedIn()}
                        <li><a href="{link Default:login}">
                                <span class="hidden-sm">{_'Přihlásit se'}</span>
                                <span class="visible-sm-inline glyphicon glyphicon-log-in" title="{_'Přihlásit se'}"/>
                            </a></li>
                        {else}
                        <li><a href="{link Default:logout}">
                                <span class="hidden-sm">{_'Odhlásit se'}</span>
                                <span class="visible-sm-inline glyphicon glyphicon-log-out" title="{_'Odhlásit se'}"/>
                            </a></li>
                        <li><a href="{link Team:default}" title="{=Interlos::getLoggedTeam()->name}">
                                <span class="hidden-sm">{=String::truncate(Interlos::getLoggedTeam()->name, 15)}</span>
                                <span class="visible-sm-inline glyphicon glyphicon-user" title="{=String::truncate(Interlos::getLoggedTeam()->name, 15)}"/>                                
                            </a></li>
                        {/if}
                        {/if}
                        <li n:if="$control->lang == 'cs'"><a href="{link this, lang => 'en'}"><img src="{$baseUri}images/icons/us-icon.png" alt="English" title="Switch to English"/></a></li>
                        <li n:if="$control->lang == 'en'"><a href="{link this, lang => 'cs'}"><img src="{$baseUri}images/icons/cz-icon.png" alt="čeština" title="Přepnout do češtiny"/></a></li>                                    
                    </ul>
                    {if Interlos::isGameActive()}
                    <p class="navbar-text navbar-right visible-lg-inline-block">{widget clock}</p>
                    {/if}

                </div><!--/.navbar-collapse -->
            </div>
        </div>

        {block #jumbotron}{/block}

        <div class="container">
            <!-- PAGE TITLE -->
            {block #title}<h1 n:ifset="$pageTitle">{$pageTitle}</h1>{/block}
            <!-- FLASH MESSAGES -->
            {widget flashMessages}
            <!-- CONTENT -->
            
            {block #bigcontent}
            <div class="row">
                <div class="col-sm-3 col-sm-push-9">
                    <div class="hidden-print affix-sm">
                        {block #subnavigation}{/block}
                    </div>
                </div>
                <div class="col-sm-9 col-sm-pull-3">
                    {block #content}{/block}
                </div>
            </div>
            {/block}

            <hr>

            <footer>
                <p class="pull-right small">{_'Pokud máte jakýkoliv dotaz, připomínku, námět apod., napište nám na naši adresu'}
                    <a href="mailto:online@fyziklani.cz">online@fyziklani.cz</a>.
                </p>
                <p><a href="http://fykos.cz/">FYKOS.cz</a></p>
            </footer>
        </div> <!-- /container -->

        <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-27814405-2']);
        _gaq.push(['_setDomainName', {$_SERVER['HTTP_HOST']}]);
        _gaq.push(['_setAllowLinker', true]);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script');
            ga.type = 'text/javascript';
            ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(ga, s);
        })();
        </script>

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <!--<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>-->
        <script src="{$baseUri}js/bootstrap.min.js"></script>
        <script src="{$baseUri}js/fix-navbar-issue.js"></script>
        <script src="{$baseUri}js/clock.js"></script>
        {/block}
    </body>
</html>
