{extends layout.phtml}

{block #content}
<div id="submenu">
        {*<a href="{$baseUri}download/fyziklani-online.pdf" title="{_'Fyziklání online'}">
                <img src="{$baseUri}download/fyziklani-online.png" alt="{!_'Fyziklání online &ndash; leták}" style="border: 1px solid #cecece; width:300px;"/>
        </a>    *}
</div>
<div id="subcontent">

<ul>
    <li>Physics contest organized by <a href="http://fykos.org/" title="The interner pyhsics competition">FYKOS</a> <a href="http://www.mff.cuni.cz/">MFF UK</a>.</li>
        <li>It takes place on <strong style="font-size:1.8em">thursday December 6, 2012 from 17:00 CET to 20:00 CET</strong>.</li>
        <li><strong>Registration opened from October 10, 2012 to December 5, 2012!</strong></li>
        <li>The contest is for 1 to 5 members in a team.</li>
        <li><strong>The translation of the website is still in progess.</strong></li>
        {*<li>Složení týmu je možné doladit i po <a href="{link :Frontend:Team:registration}">registraci</a>.</li>
        <li>
                You can expect se těšit obdobu klasického <a href="http://www.fyziklani.cz/">Fyziklání</a> a Hurry-up sérii.
        </li>

        <li>Účast je zcela zdarma.</li>
        <li><strong>Hraje se o prestiž i hmotné ceny,</strong></li>*}
</ul>
{*<p>
        Další informace najdete v <a href="{link :Frontend:Default:rules}">pravidlech</a>.
</p>*}


<p>
	If you have any questions, remarks or suggestions feel free to send us
        an email to <a href="mailto:online@fyziklani.cz" style="font-size:1.5em">online@fyziklani.cz</a>
</p>

<div id="logos">
	<a href="http://www.cuni.cz" title="Univerzita Karlova">
		<img src="{$baseUri}images/uk-logo.png" alt="Univerzita Karlova"/>
	</a>
	<a href="http://www.mff.cuni.cz" title="Matematicko-fyzikální fakulta UK">
		<img src="{$baseUri}images/mff-logo.png" alt="Matematicko-fyzikální fakulta UK" />
	</a>
	<a href="http://fykos.cz" title="Fyzikální korespondenční seminář MFF UK">
		<img src="{$baseUri}images/fykos-logo.png" alt="Fyzikální korespondenční seminář MFF UK" />
	</a>
</div>

<h2>Online Physics Brawl is brought to you by</h2>
<p><a href="http://fykos.cz/">FYKOS</a> (problems),
    <a href="http://kam.mff.cuni.cz/">Department of Applied Mathematics</a> (hardware),
    <a href="http://utf.mff.cuni.cz/">Institute of Theoretical Physics MFF UK</a> (rooms, hosting)
    a <a href="http://interlos.fi.muni.cz/">Interlos</a> (the webgame engine).
</p>

</div>

{/block}
