{extends layout.phtml}

{block title}{/block}

{block jumbotron}
<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-md-3 vcenter hidden-sm hidden-xs text-center">
                <div class="logo"></div>
            </div><!--
            --><div class="col-md-9 vcenter">
                <h1>Fyziklání online</h1>
                <p>
                    Fyzikální&hellip;
                    Mezinárodní&hellip;<br/>
                    Internetová&hellip;
                    Tříhodinová&hellip;<br/>
                    Soutěž pořádaná <a href="http://fykos.cz/" title="Fyzikální korespondenční seminář">Fyzikálním korespondenčním seminářem</a> <a href="http://www.mff.cuni.cz/">MFF UK</a>.
                </p>
                {if Interlos::isRegistrationActive() && !Environment::getUser()->isLoggedIn()}
                <p><a class="btn btn-primary btn-lg" href="{link :Frontend:Team:registration}" role="button">Registrace &raquo;</a></p>
                {/if}
            </div>
        </div>

    </div>
</div>
{/block}

{block content}


<div class="row">
    <div class="col-md-4">        
        <h2>Kdy</h2>
        {if Interlos::isGameEnd()}
        <p>Proběhla ve <strong n:block='game_period'>{$year->game_start|date:'%A %e. %#m.'|lower} od {$year->game_start|date:'%k.%M'} do {$year->game_end|date:'%k.%M'}</strong>.</p>
        {else}
        <p>Proběhne ve {include #game_period}.</p>
        <p>Registrace otevřena {if !Interlos::isRegistrationStarted()}od {$year->registration_start|date:'%d. %#m. %Y'} {/if}<strong>do {$year->registration_end|date:'%d. %#m. %Y %k.%M'}</strong>.</p>
        {/if}
    </div>
    <div class="col-md-4">
        <h2>Jak</h2>
        <p>Fyziklání online je tříhodinová týmová hra probíhající přes Internet.</p>
        <p>Soutěžit můžou 1&ndash;5členné týmy v několika kategoriích.</p>
        <p>Můžete se těšit obdobu klasického <a href="http://www.fyziklani.cz/">Fyziklání</a> a Hurry-up sérii.</p>
        <p><a class="btn btn-default" href="{link Default:rules}" role="button">Pravidla &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Proč</h2>
        <p><strong>Hraje se o prestiž i hmotné ceny,</strong> oceněno bude prvních pět týmů v každé z kategorií A, B, C a jeden tým v kategorii open, který je z ČR nebo SR.</p>
        <p><a href="{$baseUri}download/2013-1/knihy.pdf">Příklady knih</a> a <a href="{$baseUri}download/2013-1/hry.pdf">příklady her</a>.</p>
        <p>Účast je zcela zdarma.</p>        
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <h3>Fyziklání online mají na svědomí</h3>
        <p>organizátoři <a href="http://fykos.cz/">FYKOSu</a> (příprava, úlohy),
            <a href="http://utf.mff.cuni.cz/">Ústav teoretické fyziky MFF UK</a> (prostory, hosting)
            <a href="http://kam.mff.cuni.cz/">Katedra aplikované matematiky MFF UK</a> (železo),
            <a href="http://www.msmt.cz/">Ministerstvo školství, mládeže a&nbsp;tělovýchovy</a>&nbsp;(spoluvyhlašovatel),
            <a href="http://interlos.fi.muni.cz/">Interlos</a> (základ herního systému),
            <a href="http://www.cez.cz/">Skupina ČEZ</a> (sponzor).
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <a href="http://www.cuni.cz" title="Univerzita Karlova v Praze">
            <img src="{$baseUri}images/uk-logo.png" alt="Univerzita Karlova v Praze"/>
        </a>
    </div>
    <div class="col-md-2"><a href="http://www.mff.cuni.cz" title="Matematicko-fyzikální fakulta UK">
            <img src="{$baseUri}images/mff-logo.png" alt="Matematicko-fyzikální fakulta UK" />
        </a>
    </div>
    <div class="col-md-2"><a href="http://fykos.cz" title="Fyzikální korespondenční seminář MFF UK">
            <img src="{$baseUri}images/fykos-logo.png" alt="Fyzikální korespondenční seminář MFF UK" />
        </a>
    </div>
    <div class="col-md-2"><a href="http://www.msmt.cz/" title="Ministerstvo školství, mládeže a tělovýchovy">
            <img src="{$baseUri}images/msmt-logo.png" alt="Ministerstvo školství, mládeže a tělovýchovy" />
        </a>
    </div>
    <div class="col-md-2"><a href="http://www.cez.cz/" title="Skupina ČEZ">
            <img src="{$baseUri}images/cez-logo.png" alt="Skupina ČEZ" />
        </a>
    </div>
</div>

{/block}



