{extends layout.phtml}

{block #content}
<div id="submenu">
        <a href="{$baseUri}download/2012-2/letak-cs.pdf" title="{_'Fyziklání online'}">
                <img src="{$baseUri}download/2012-2/letak-cs.png" alt="{!_'Fyziklání online &ndash; leták}" style="border: 1px solid #cecece; width:300px;"/>
        </a>   
</div>
<div id="subcontent">

<ul>
    <li>Fyzikální soutěž pořádaná <a href="http://fykos.cz/" title="Fyzikální korespondenční seminář">Fyzikálním korespondenčním seminářem</a> <a href="http://www.mff.cuni.cz/">MFF UK</a>.</li>
{if Interlos::isGameEnd()}
        <li>Proběhla ve <strong style="font-size:1.8em">čtvrtek 6. prosince 2012 od 17:00 do 20:00</strong>.</li>
        <li><strong>Registrace byla otevřena od 10. 10. 2012 do 5. 12. 2012!</strong></li>
{else}
        <li>Proběhne ve <strong style="font-size:1.8em">čtvrtek 6. prosince 2012 od 17:00 do 20:00</strong>.</li>
        <li><strong>Registrace otevřena od 10. 10. 2012 do 5. 12. 2012!</strong></li>
{/if}
        <li>Složení týmu je možné doladit i po <a href="{link :Frontend:Team:registration}">registraci</a>.</li>
        <li>
                Můžete se těšit obdobu klasického <a href="http://www.fyziklani.cz/">Fyziklání</a> a Hurry-up sérii.
        </li>
        <li>Soutěžit můžou 1&ndash;5členné týmy v několika kategoriích.</li>
        <li>Účast je zcela zdarma.</li>
        <li><strong>Hraje se o prestiž i hmotné ceny,</strong></li>
	<li><a href="{$baseUri}download/2012-2/knihy.pdf">seznam knih</a> a <a href="{$baseUri}download/2012-2/hry.pdf">seznam her</a></li>
</ul>
<p>
        Další informace najdete v <a href="{link :Frontend:Default:rules}">pravidlech</a>.
</p>


<p>
	Pokud máte jakýkoliv dotaz, připomínku, námět apod.,
	napište nám na naši adresu <a href="mailto:online@fyziklani.cz" style="font-size:1.5em">online@fyziklani.cz</a>
</p>

<div id="logos">
	<a href="http://www.cuni.cz" title="Univerzita Karlova">
		<img src="{$baseUri}images/uk-logo.png" alt="Univerzita Karlova"/>
	</a>
	<a href="http://www.mff.cuni.cz" title="Matematicko-fyzikální fakulta UK">
		<img src="{$baseUri}images/mff-logo.png" alt="Matematicko-fyzikální fakulta UK" />
	</a>
	<a href="http://fykos.cz" title="Fyzikální korespondenční seminář MFF UK">
		<img src="{$baseUri}images/fykos-logo.png" alt="Fyzikální korespondenční seminář MFF UK" />
	</a>
</div>

<h2>Fyziklání online mají na svědomí</h2>
<p>organizátoři <a href="http://fykos.cz/">FYKOSu</a> (příprava, úlohy),
    <a href="http://kam.mff.cuni.cz/">Katedra aplikované matematiky MFF UK</a> (železo),
    <a href="http://utf.mff.cuni.cz/">Ústav teoretické fyziky MFF UK</a> (prostory, hosting)
    a <a href="http://interlos.fi.muni.cz/">Interlos</a> (základ herního systému).
</p>

</div>

{/block}
