{extends layout.phtml}

{block #content}
<div id="submenu">
        <a href="{$baseUri}download/2012-2/leaflet.pdf" title="{_'Fyziklání online'}">
                <img src="{$baseUri}download/2012-2/leaflet.png" alt="{!_'Fyziklání online &ndash; leták}" style="border: 1px solid #cecece; width:300px;"/>
        </a>   
</div>
<div id="subcontent">

<ul>
    <li> Online physics competition organized by <a href="http://fykos.org/" title="The interner pyhsics competition">FYKOS</a> <a href="http://www.mff.cuni.cz/">MFF UK</a>.</li>
{if Interlos::isGameEnd()}
        <li>It took place on <strong style="font-size:1.8em">Thursday December 6, 2012 from 17:00 UTC+1 to 20:00 UTC+1</strong>.</li>
        <li><strong>Registration was open from October 10, 2012 to December 5, 2012!</strong></li>
{else}
        <li>It takes place on <strong style="font-size:1.8em">Thursday December 6, 2012 from 17:00 UTC+1 to 23:59 UTC+1</strong>.</li>
        <li><strong>Registration is open from October 10, 2012 to December 5, 2012!</strong></li>
{/if}
        <li>The competition is for teams of up to five people.</li>
        <li>You can add (or change) members of your team even after you <a href="{link :Frontend:Team:registration}">sign up</a>.</li>
        <li>
                You can look forward to a modification of our classic <a href="http://www.fyziklani.cz/">Physics Brawl</a> (known to Czech students only, sorry) and a Hurry-up problem series.
        </li>

        <li>Participation is free.</li>
        <li><strong>Try and win the best imaginable prize ever &ndash; fame.</strong></li>
</ul>
{*<p>
        For more information check out the official <a href="{link :Frontend:Default:rules}">rules</a>.
</p>*}


<p>
	If you have any questions, remarks, or suggestions please send us
        an email to <a href="mailto:online@fyziklani.cz" style="font-size:1.5em">online@fyziklani.cz</a>
</p>

<div id="logos">
	<a href="http://www.cuni.cz" title="Univerzita Karlova">
		<img src="{$baseUri}images/uk-logo.png" alt="Univerzita Karlova"/>
	</a>
	<a href="http://www.mff.cuni.cz" title="Matematicko-fyzikální fakulta UK">
		<img src="{$baseUri}images/mff-logo.png" alt="Matematicko-fyzikální fakulta UK" />
	</a>
	<a href="http://fykos.cz" title="Fyzikální korespondenční seminář MFF UK">
		<img src="{$baseUri}images/fykos-logo.png" alt="Fyzikální korespondenční seminář MFF UK" />
	</a>
</div>

<h2>Online Physics Brawl is brought to you by</h2>
<p><a href="http://fykos.cz/">FYKOS</a> (problems),
    <a href="http://kam.mff.cuni.cz/">Department of Applied Mathematics</a> (hardware),
    <a href="http://utf.mff.cuni.cz/">Institute of Theoretical Physics, MFF UK</a> (rooms, hosting)
    a <a href="http://interlos.fi.muni.cz/">Interlos</a> (the webgame engine).
</p>
<p id="banners">
    <a href="http://www.mff.cuni.cz/admission/"><img src="{$baseUri}download/2012-2/banner234_60znak.jpg" alt="Study compuer science at Charles University"/></a>
</p>

</div>

{/block}
