{extends layout.phtml}

{block #content}

<h2 id="2013-1">prosinec 2013</h2>
<ul>
    <li><a href="{link Archive:a201312results}">výsledkovka kategorií</a>,
        <a href="{link Archive:a201312detail}">podrobná výsledkovka</a> a
        <a href="{link Archive:a201312tasks}">statistiky úloh</a></li>
    <li>Vítězové v kategorii Středoškoláci A: <strong>m.raszyk</strong> Martin Raszyk</li>
    <li>Vítězové v kategorii Středoškoláci B: <strong>Qaterknan</strong> Jirka Balhar, Štěpán Paulík, Martin Mach, Hynek Fencl, Štěpán Marek </li>
    <li>Vítězové v kategorii Středoškoláci C: <strong>60letGymtri</strong> Lukáš Supik, Jiří Mravec, Markéta Kubiková, Kamil Cinkraut, Štěpán Stenchlák</li>
    <li>Vítězové v kategorii Zahraniční SŠ: <strong>Yognau(gh)ts</strong> Vilda Kornelija Markevičiūtė, Gintautas Kamuntavičius</li>
    <li>Vítězové v kategorii Open: <strong>Veterani</strong> Selver Pepić, Admir Greljo, Alija Bevrnja, Sladjan Veselinović, Amer Ajanović </li>

</ul>
<p>
    Z tohoto ročníku si můžete stáhnout <a href="{$baseUri}download/2013-1/ulohy/reseni.cs.pdf">zadání a řešení</a> všech úloh.
</p>

<h2 id="2012-2">prosinec 2012</h2>
<ul>
    <li><a href="{link Archive:a201212results}">výsledkovka kategorií</a>,
        <a href="{link Archive:a201212detail}">podrobná výsledkovka</a> a
        <a href="{link Archive:a201212tasks}">statistiky úloh</a></li>
    <li>Vítězové v kategorii Středoškoláci A: <strong>Okarusov Bleck</strong> Patrik Turzák, Lubomír Grund, Ján Ondráš, Milan Pešta, Michal Staruch</li>
    <li>Vítězové v kategorii Středoškoláci B: <strong>Ešte ďalej</strong> Marek Bašista, Jakub Šafin, Vladimír Macko, Eduard Batmendijn </li>
    <li>Vítězové v kategorii Středoškoláci C: <strong>Gymtri1</strong> Kamil Cinkraut, Markéta Kubiková, Lucie Pejšková, Dominik Sedlařík, Lukáš Supik</li>
    <li>Vítězové v kategorii Zahraniční SŠ: <strong>bieber</strong> Ryan Kartiko, Justian Harkho, Kristo Nugraha Lian, Josephine Monica</li>
    <li>Vítězové v kategorii Open: <strong>kTP^2/(MJ) = MaKaJ ToPře</strong> Martin Čížek, Jiří Eliášek, Přemysl Kolorenč, Karel Houfek, Tomáš Ledvinka</li>

</ul>
<p>
    Z tohoto ročníku si můžete stáhnout <a href="{$baseUri}download/2012-2/ulohy/reseni.cs.pdf">zadání a řešení</a> všech úloh.            
</p>

<h2 id="2012-1">květen 2012</h2>
<ul>
    <li><a href="{link Archive:a201205results}">výsledkovka kategorií</a>,
        <a href="{link Archive:a201205detail}">podrobná výsledkovka</a> a
        <a href="{link Archive:a201205tasks}">statistiky úloh</a></li>
    <li>Vítězové v kategorii středoškoláků: <strong>Makaci</strong> Eduard Batmendijn, Jakub Šafin, Mark Daniel, Roman Hudec, Samuel Horváth</li>
    <li>Vítězové v kategorii open: <strong>modré elektróny</strong> Fridrich Valach, Lukáš Konečný, Mária Kieferová, Márius Kádek, Samuel Kováčik</li>

</ul>
<p>
    Z tohoto ročníku si můžete stáhnout <a href="{$baseUri}download/2012-1/ulohy/reseni.pdf">zadání a řešení</a> všech úloh.            
</p>
<blockquote>
    <p>Naše celkové hodnocení Fyziklání online je jen a jen pozitivní. Byla to opět skvělá příležitost vyzkoušet si i jiné typy příkladů, než jaké se vyskytují v učebnicích nebo olympiádě a zároveň poměřit své schopnosti v řešení fyzikálních úloh s ostatními.</p>

    <p>Fyziklání pro nás představovalo příjemně strávené pozdní odpoledne ve společnosti skvělých lidí a fyziky. I když členové našeho týmu jsou roztroušeni po celé republice, velmi se vyplatilo osobně se sejít na jednom místě, ne jen kvůli atmosféře, ale hlavně kvůli efektivnější komunikaci.</p>
    <p>K samotnému průběhu soutěže nemáme moc co dodat. Organizace byla perfektní, vyskytlo se pouze pár menších technických problému, které ovšem byly brzy vyřešeny. Stejně tak nápad na jiné strukturování příkladů (hurry-up série), než jaké je u tradičního Fyziklání, se u nás setkal jen s kladnými ohlasy.</p>
    <p>I když prezenční forma Fyziklání je ve všech směrech přece jen lepší, tato online obdoba měla také své kouzlo. Každému bychom účast jen doporučili, rozhodně to stojí za to. Těšíme se na další ročník!</p>

    <footer>Za tým Amazingní Starvace Veronika Dočkalová</footer>
</blockquote>
{/block}

{block #subnavigation}
<ul class="nav">
    <li><a href="#2013-1">prosinec 2013</a></li>	
    <li><a href="#2012-2">prosinec 2012</a></li>	
    <li><a href="#2012-1">květen 2012</a></li>	
</ul>
{/block}
