{extends layout.phtml}

{block #content}
    <div id="submenu">
	<ul>
	    <li><a href="#2012-1">May 2012</a></li>	
	</ul>
    </div>
    <div id="subcontent">
	<h2 id="2012-1">May 2012</h2>
        <ul>
	    <li><a href="{link Archive:results201205}">results</a>,
                <a href="{link Archive:detail201205}">more detailed results</a> a
                <a href="{link Archive:tasks201205}"></a>problem statistics</li>
	    <li>Winners in the category of high school students: <strong>Makaci</strong> Eduard Batmendijn, Jakub Šafin, Mark Daniel, Roman Hudec, Samuel Horváth</li>
	    <li>Winners in the open category: <strong>modré elektróny</strong> Fridrich Valach, Lukáš Konečný, Mária Kieferová, Márius Kádek, Samuel Kováčik</li>
	    
	</ul>
	<p>
	    You can check out the <a href="{$baseUri}download/2012-1/reseni.zip">problems and solutions</a> from the May competition.
	</p>
        <blockquote>
            <p>Our review of the Online Physics Brawl is only positive. It was a great opportunity to try solving problems that are very different from the ones you can find in textbooks or competitions like the Physics Olympiad. It also enabled us to compare our problem solving skills with other students.</p>
            
            <p>Physics Brawl was a great way to spend a late afternoon in the company of amazing people and physics. Although the members of our team are scattered all over the country, it paid off that we met at one place since we had a great time hanging out together, and it helped to make the communication more effective.</p>
            <p>The organization of the competition was perfect. There were only a few technical problems that were swiftly taken care of. Also we appreciated the addition of the Hurry-up series that is not normally present in the Physics Brawl.
</p>
            <p>Although the classic Physics Brawl is better in every way, this online version was very enjoyable as well. We would definitely recommened to participate. It was a great experience, and we are looking forward to competing next year!
</p>
            <p>A member of the team Amazingní Starvace<br/>
            Veronika Dočkalová</p>
        </blockquote>
    </div>
{/block}
