{extends layout.phtml}

{block #content}
    <div id="submenu">
	<ul>
	    <li><a href="#2012-1">květen 2012</a></li>	
	</ul>
    </div>
    <div id="subcontent">
	<h2 id="2012-1">květen 2012</h2>
        <ul>
	    <li><a href="{link Archive:results2012_1}">výsledkovka kategorií</a>,
                <a href="{link Archive:detail2012_1}">podrobná výsledkovka</a> a
                <a href="{link Archive:tasks2012_1}">statistiky úloh</a></li>
	    <li>Vítězové v kategorii středoškoláků: <strong>Makaci</strong> Eduard Batmendijn, Jakub Šafin, Mark Daniel, Roman Hudec, Samuel Horváth</li>
	    <li>Vítězové v kategorii open: <strong>voymodré elektróny</strong> Fridrich Valach, Lukáš Konečný, Mária Kieferová, Márius Kádek, Samuel Kováčik</li>
	    
	</ul>
	<p>
	    Z tohoto ročníku si můžete stáhnout <a href="{$baseUri}download/2012-1/reseni.zip">zadání a řešení</a> všech úloh.            
	</p>        
    </div>
{/block}
