{extends layout.phtml}

{block #content}
    <div id="submenu">
	<ul>
	    <li><a href="#2012-1">květen 2012</a></li>	
	</ul>
    </div>
    <div id="subcontent">
	<h2 id="2012-1">květen 2012</h2>
        <ul>
	    <li><a href="{link Archive:results201205}">výsledkovka kategorií</a>,
                <a href="{link Archive:detail201205}">podrobná výsledkovka</a> a
                <a href="{link Archive:tasks201205}">statistiky úloh</a></li>
	    <li>Vítězové v kategorii středoškoláků: <strong>Makaci</strong> Eduard Batmendijn, Jakub Šafin, Mark Daniel, Roman Hudec, Samuel Horváth</li>
	    <li>Vítězové v kategorii open: <strong>modré elektróny</strong> Fridrich Valach, Lukáš Konečný, Mária Kieferová, Márius Kádek, Samuel Kováčik</li>
	    
	</ul>
	<p>
	    Z tohoto ročníku si můžete stáhnout <a href="{$baseUri}download/2012-1/reseni.zip">zadání a řešení</a> všech úloh.            
	</p>
        <blockquote>
            <p>Naše celkové hodnocení Fyziklání online je jen a jen pozitivní. Byla to opět skvělá příležitost vyzkoušet si i jiné typy příkladů, než jaké se vyskytují v učebnicích nebo olympiádě a zároveň poměřit své schopnosti v řešení fyzikálních úloh s ostatními.</p>
            
            <p>Fyziklání pro nás představovalo příjemně strávené pozdní odpoledne ve společnosti skvělých lidí a fyziky. I když členové našeho týmu jsou roztroušeni po celé republice, velmi se vyplatilo osobně se sejít na jednom místě, ne jen kvůli atmosféře, ale hlavně kvůli efektivnější komunikaci.</p>
            <p>K samotnému průběhu soutěže nemáme moc co dodat. Organizace byla perfektní, vyskytlo se pouze pár menších technických problému, které ovšem byly brzy vyřešeny. Stejně tak nápad na jiné strukturování příkladů (hurry-up série), než jaké je u tradičního Fyziklání, se u nás setkal jen s kladnými ohlasy.</p>
            <p>I když prezenční forma Fyziklání je ve všech směrech přece jen lepší, tato online obdoba měla také své kouzlo. Každému bychom účast jen doporučili, rozhodně to stojí za to. Těšíme se na další ročník!</p>

            <p>Za tým Amazingní Starvace<br/>
            Veronika Dočkalová</p>
        </blockquote>
    </div>
{/block}
