{extends layout.phtml}

{block #content}

<h2 id="2013-1">December 2013</h2>
<ul>
    <li><a href="{link Archive:a201312results}">results</a>,
        <a href="{link Archive:a201312detail}">more detailed results</a> and
        <a href="{link Archive:a201312tasks}">problem statistics</a></li>
    <li>Winners in the category High school outside of Czech Republic: <strong>Yognau(gh)ts</strong> Vilda Kornelija Markevičiūtė, Gintautas Kamuntavičius</li>
    <li>Winners in the category Open: <strong>Veterani</strong> Selver Pepić, Admir Greljo, Alija Bevrnja, Sladjan Veselinović, Amer Ajanović </li>
    <li>Winners in the category High school students A: <strong>m.raszyk</strong> Martin Raszyk</li>
    <li>Winners in the category High school students B: <strong>Qaterknan</strong> Jirka Balhar, Štěpán Paulík, Martin Mach, Hynek Fencl, Štěpán Marek </li>
    <li>Winners in the category High school students C: <strong>60letGymtri</strong> Lukáš Supik, Jiří Mravec, Markéta Kubiková, Kamil Cinkraut, Štěpán Stenchlák</li>

</ul>
<p>
    You can take a look at the <a href="{$baseUri}download/2013-1/ulohy/reseni.en.pdf">problems and solutions</a>.
</p>

<h2 id="2012-2">December 2012</h2>
<ul>
    <li><a href="{link Archive:a201212results}">results</a>,
        <a href="{link Archive:a201212detail}">more detailed results</a> and
        <a href="{link Archive:a201212tasks}">problem statistics</a></li>
    <li>Winners in the category High school outside of Czech Republic: <strong>bieber</strong> Ryan Kartiko, Justian Harkho, Kristo Nugraha Lian, Josephine Monica</li>
    <li>Winners in the category Open: <strong>kTP^2/(MJ) = MaKaJ ToPře</strong> Martin Čížek, Jiří Eliášek, Přemysl Kolorenč, Karel Houfek, Tomáš Ledvinka</li>
    <li>Winners in the category High school students A: <strong>Okarusov Bleck</strong> Patrik Turzák, Lubomír Grund, Ján Ondráš, Milan Pešta, Michal Staruch</li>
    <li>Winners in the category High school students B: <strong>Ešte ďalej</strong> Marek Bašista, Jakub Šafin, Vladimír Macko, Eduard Batmendijn </li>
    <li>Winners in the category High school students C: <strong>Gymtri1</strong> Kamil Cinkraut, Markéta Kubiková, Lucie Pejšková, Dominik Sedlařík, Lukáš Supik</li>

</ul>
<p>
    You can take a look at the <a href="{$baseUri}download/2012-2/ulohy/reseni.en.pdf">problems and solutions</a>.
</p>

<h2 id="2012-1">May 2012</h2>
<ul>
    <li><a href="{link Archive:a201205results}">results</a>,
        <a href="{link Archive:a201205detail}">more detailed results</a> and
        <a href="{link Archive:a201205tasks}">problem statistics</a></li>
    <li>Winners in the category of high school students: <strong>Makaci</strong> Eduard Batmendijn, Jakub Šafin, Mark Daniel, Roman Hudec, Samuel Horváth</li>
    <li>Winners in the open category: <strong>modré elektróny</strong> Fridrich Valach, Lukáš Konečný, Mária Kieferová, Márius Kádek, Samuel Kováčik</li>

</ul>
<p>
    You can check out the <a href="{$baseUri}download/2012-1/ulohy/reseni.pdf">problems and solutions</a> from the May competition (in Czech only).
</p>
<blockquote>
    <p>Our review of the Online Physics Brawl is only positive. It was a great opportunity to try solving problems that are very different from the ones you can find in textbooks or competitions like the Physics Olympiad. It also enabled us to compare our problem solving skills with other students.</p>

    <p>Physics Brawl was a great way to spend a late afternoon in the company of amazing people and physics. Although the members of our team are scattered all over the country, it paid off that we met at one place since we had a great time hanging out together, and it helped to make the communication more effective.</p>
    <p>The organization of the competition was perfect. There were only a few technical problems that were swiftly taken care of. Also we appreciated the addition of the Hurry-up series that is not normally present in the Physics Brawl.
    </p>
    <p>Although the classic Physics Brawl is better in every way, this online version was very enjoyable as well. We would definitely recommened to participate. It was a great experience, and we are looking forward to competing next year!
    </p>
    <footer>A member of the team Amazingní Starvace Veronika Dočkalová</footer>
</blockquote>
{/block}
{block #subnavigation}
<ul class="nav">
    <li><a href="#2013-1">December 2013</a></li>	
    <li><a href="#2012-2">December 2012</a></li>	
    <li><a href="#2012-1">May 2012</a></li>	
</ul>

{/block}
