{extends layout.phtml}

{block #content}
<div id="submenu">
    <ul>
        <li><a href="#participation">Účast ve hře</a></li>
        <li><a href="#tasks">Úlohy</a></li>
        <li><a href="#system">Systém hry a bodování</a></li>
        <li><a href="#equipment">Vybavení</a></li>
        <li><a href="#advices">Rady</a></li>
        <li><a href="#awards">Odměny</a></li>
    </ul>
</div>
<div id="subcontent">
    <ul>
        <li>Fyziklání online je tříhodinová týmová hra probíhající přes Internet.</li>
        <li>Týmy řeší zadané úlohy, řešením každé úlohy je číslo, které odesílají přes webový formulář.</li>
        <li>Za vyřešené úlohy získávají týmy body, během hry týmy stále vidí aktuální výsledkovou listinu, která bude 20 minut před koncem soutěže zmražena
            a opět aktualizována až po skončení hry.</li>
    </ul>

    <h2 id="participation">Účast ve hře</h2>
<ul>
    <li>Hrají týmy skládající se z 1&ndash;5 hráčů. </li>
    <li>
        Každý tým se zařadí do jedné ze dvou kategorií:
        <ul>
            <li><strong>středoškoláci</strong> &ndash; všichni členové týmu musí být studenti střední (nebo základní) školy, tzn. žádný student nestuduje vysokou školu a všichni členové týmu jsou mladší 20 let.</li>
            <li><strong>open</strong> &ndash; kdokoliv.</li>
        </ul>
    </li>
    <li>Kategorie středoškoláků bude dále rozdělena na tři podkategorie podle věku jejích členů.
        Studenti mladší prvního ročníku čtyřletého gymnázia si přiřadí koeficient hráče 0, studenti prvního ročníku koeficient hráče 1, druhého 2, atd.
        koeficient týmu týmu se spočte jako průměrná hodnota koeficientů hráčů (koeficienty hráče od jednotlivých členů se sečtou a vydělí počtem členů týmu).
        Tým se zařadí do nejnižší kategorie, která mu vyhovuje:
        <ul>
            <li><strong> středoškoláci C</strong> koeficient týmu &le; 2 &amp; žádný člen týmu nemá koeficient hráče 4 &amp; max. dva členové týmu mají koeficient hráče 3,</li>
            <li><strong> středoškoláci B</strong> koeficient týmu &le; 3 &amp; max. dva členové týmu mají koeficient hráče 4, </li>
            <li><strong> středoškoláci A</strong> koeficient týmu &le; 4.</li>
        </ul>
            </li>
    <li>Týmy ve všech kategoriích budou mít úplně stejné úlohy. Pro každou kategorii bude samostatná výsledková listina, navíc bude i celková výsledková listina.</li>
    <li>Účast na hře je zdarma.</li>
    <li>Odměnou za dobré umístění je prestiž a dobrý pocit, pro nejlepší středoškoláky jsou připraveny také ceny hmotné.</li>
    <li>Je zakázána jakákoliv spolupráce mezi týmy.</li>
    <li>Hra je založena na fair-play. Průběh hry monitorujeme a můžeme tedy odhalit některé způsoby podvádění, nicméně předpokládáme, že hrajete proto, abyste si zahráli, a tudíž že podvádění nemá smysl.</li>
    <li>Všichni členové týmu svým přihlášením do soutěže souhlasí se zpracováním poskytnutých dat pro účely vyhodnocení soutěže a jejího dalšího zlepšování.</li>
</ul>

<h2 id="tasks">Úlohy</h2>
<ul>
    <li>Zadání úloh budou zveřejněna ve formátu <acronym title="Portable Document Format">PDF</acronym> na webu hry po přihlášení týmovým heslem.</li>
    <li>Výsledkem úlohy je číslo. V zadání úlohy bude, zda požadujeme číslo celé (vysloveně) nebo reálné (výchozí). U reálného čísla se bude<!-- zadán požadovaný počet platných cifer a--> jeho vyhodnocování provádět v rámci intervalu tolerance.</li>
    <li>Je-li v zadání uvedena číselná hodnota nějaké konstanty, použijte striktně tuto hodnotu.</li>
    <li>Číselné výsledky úloh uvádějte v nenásobných jednotkách SI, není-li
uvedeno jinak. U každého příkladu je uveden minimální počet požadovaných platných cifer, ačkoli je možné, že váš výsledek bude správný i při menším počtu zadaných míst, jen dodržení vám zaručí správnou opravu výsledku. Příklady:
    <ul>
        <li><em>Jakou vzdálenost ujede vlak rychlostí 50 km/h za minutu? Uveďte alespoň 4 platné cifry.</em> &mdash; třeba odpověď 833,3 nebo 833,33</li>
        <li><em>Kolik kilometrů ujede vlak rychlostí 50 km/h za minutu? Stačí 1 platná cifra.</em> &mdash; třeba odpověď 0,8</li>
        <li><em>Kolik atomů uhlíku (celé číslo) obsahuje molekula cyklopentanoperhydrofenantrenu?</em> &mdash; odpověď 17 &mdash; 17,0001 je špatně</li>
    </ul>
    </li>
    <li>Úlohy budou rozmanitých typů a rozmanité obtížnosti, která bude rozlišena maximem možných získaných bodů, jednodušší úlohy bude obsahovat <em>Hurry-up</em> série, ale bude na jejich řešení méně času.</li>
</ul>

<h2 id="system">Systém hry a bodování</h2>
<ul>
    <li>
        Hra bude mít tři části:
        <ul>
            <li>První část: 17:00 až 18:30.</li>
            <li>Druhá část: 18:30 až 20:00.</li>
            <li><em>Hurry-up</em> část: 18:00 až 18:30.</li>
        </ul>
    </li>
    <li>Konec hry je ve 20:00 (3 hodiny po začátku hry).</li>
    <li>V první části bude zadáno každému týmu 5 úloh, po vyřešení úlohy se týmu zpřístupní další příklad v sérii.</li>
    <li>
        Za úlohy získávají týmy body. U každé úlohy je určen maximální počet bodů, které tým získá, pokud odpoví na úlohy správně napoprvé.
        Při prvním opakování odpovědi získává tým 0,6-násobek maxima,
        dále analogicky 0,4-násobek a 0,2-násobek,
        minimální počet bodů, který získá je ale 1 bod.
        Násobky se zaokrouhlují nahoru na celý bod.</li>
    <li>Při špatné odpovědi bude týmu na 1 minutu znemožněno odpovídat na úlohy dané skupiny.</li>
    <li>Druhá část na tu první spojitě naváže a její bodování je stejné. Pokračuje se řešením stejných příkladů, včetně těch, které již máte k dispozici, popřípadě máte rozpracované. Týmy ale navíc získají možnost na nevyřešenou úlohu neodpovídat a otevřít si místo ní jinou, za toto bude tým penalizován jedním bodem.</li>
    <li>V případě rovnosti bodů rozhoduje nižší čas zpracování poslední správné odpovědi.</li>
</ul>
    <h3>Hurry-up</h3>
    <ul>
        <li>Hodinu po začátku se otevře možnost odpovídat na úlohy tzv. <em>Hurry-up</em> série.</li>
        <li>Úlohy této části lze odevzdávat jenom půl hodiny (avšak souběžně s první částí).</li>
        <li>Úlohy jsou rozděleny na tři tematické oddíly. Na počátku dostane tým z každého oddílu jeden příklad.
        Po správné odpovědi se týmu zpřístupní další úloha daného oddílu.</li>
        <li>Za každou zkompletovanou trojici (tj. správně zodpovězené úlohy daného pořadí z každého oddílu)
            bude tým odměněn bonusem ve výši bodů získaných za úlohy dané trojice.</li>
        <li>Za špatnou odpověď na úlohu <em>Hurry-up</em> série se počet bodů získatelných za její vyřešení
        o jeden bod sníží a to až na hranici 0 bodů!</li>
    </ul>
    
</ul>

<h2 id="equipment">Vybavení</h2>
<ul>
    <li>Počítač s přístupem na Internet (rychlost připojení by neměla být příliš důležitá). Více počítačů může být výhodou (ale není nezbytně nutné). Je dovoleno používat Internet jako zdroj informací v libovolné míře.</li>
    <li>Tiskárna není nutná, ale může vám pomoci.</li>
    <li>Papíry, tužky, pastelky, podložky, literatura, kalkulačka, &hellip;</li>
    <li>Svačina.</li>
    <li>Maskot týmu (nejlépe pták Fykosák).</li>
</ul>

<h2 id="advices">Rady</h2>
<ul>
    <li>Větší tým má výhodu, doporučujeme pětičlenné týmy.</li>
    <li>U hry je důležitou součástí i celková strategie: Které úlohy je výhodné řešit? Je lepší pracovat společně nebo si práci rozdělit a pracovat samostatně? Kdo rozhoduje, jak si tým rozdělí práci? Během hry budete zavaleni úkoly, zkuste si tedy strategii prodiskutovat dopředu.</li>
    <li> Během hry máte k dispozici výsledkovou listinu a statistiky úloh - z těchto informací můžete poznat, které úlohy jsou jednoduché a které těžké a tomu můžete přizpůsobit svoji strategii. Sledujte tedy pravidelně výsledkovku!</li>
</ul>
<h2 id="awards">Odměny (pro květen 2012)</h2>
<ul>
    <li>Mimo nehynoucí slávy jsou odměnami i <strong>společenské hry a knížky</strong>.</li>
    <li>V kategorii středoškoláků bude odměno prvních pět týmů.
        <ul>
            <li>1. 1 hra, 5 knížek</li>
            <li>2. 2 hry, 2 knížky</li>
            <li>3. 1 hra, 2 knížky</li>
            <li>4. 1 hra, 1 knížka</li>
            <li>5. 1 hra</li>
        </ul></li>
    <li>Vítězná skupina kategorie Open získá hru <strong>Pentago</strong>.</li>
    <li>Zmíněné týmy si mohou vybrat ceny z dané množiny, týmy výše v žebříčku však mají přednost.</li>
    <li><a href="{$baseUri}download/2012-1/knizky.pdf">Seznam knížek pro vítěze</a>.</li>
    <li><a href="{$baseUri}download/2012-1/hry.pdf">Seznam her pro vítěze</a>.</li>
</ul>
</div>
{/block}
