{extends layout.phtml}

{block #content}
<ul>
    <li>Online Physics Brawl is a three-hour long team competition taking place on the Internet. </li>
    <li>Participating teams compete in the solving of short physics problems. The solution to every problem is a number that is sent to our servers using a web form. </li>
    <li>Teams are awarded points for successfully solved problems. During the competition, the score of each team is visible to every other team until 20 minutes before the end. At that point, the scores are hidden and not shown to the participants again until the competition is finished.</li>
</ul>

<h2 id="participation">Basic information</h2>
<ul>
    <li>Teams consist of 1&ndash;5 players.</li>
    <li>
        Every team is a member of one of the following two categories:
        <ul>
            <li><strong>high school students</strong> &ndash; every team member must be enrolled in a high school (or in a middle school/elementary school), and no member can be older than 20 years</li>
            <li><strong>open</strong> &ndash; everyone who cannot or does not want to be in the first category.</li>
        </ul>
    </li>
    <li>Teams are solving the same problems no matter what category they are in. Winners of each category will be announced separately. Absolute winners will be announced as well. </li>
    <li>Participation in the competition is free.</li>
    <li>The award for the best teams is the eternal fame gained by winning a competition like this.</li>
    <li>Collaboration among different teams is not allowed.</li>
    <li>While we monitor the competition, it is easy to cheat. We assume all the teams participate because they want to have fun competing. Cheating will spoil this purpose.</li>
    <li>All members of the team agree with processing their personal information by registering into the competition. Your information will be used for appraisal of the competition and its improving.</li>
</ul>

<h2 id="tasks">Problems</h2>
<ul>
    <li>Problems will be available on the web of the competition in the form of a <acronym title="Portable Document Format">PDF</acronym> file. You will need your team's password to access the problems.</li>
<li>The answer to a problem is always a number. Unless otherwise stated, you should assume that this number is real. The minimum number of significant digits we expect to see will be stated in each problem. Check this before submitting your answer! You do not need to worry about numerical inaccuracies, rounding up etc. since each problem will have a range of correct answers.</li>
<li>If there is a numerical value of a certain constant in the problem statement, you should use exactly this value in your calculations.</li>
<li>Unless otherwise stated, answeres should be expressed in the base SI units. Examples:
    <ul>
        <li><em>A train is moving at a speed of 50 km/h. What is the distance it travels in a minute? State your answer to at least 4 significant digits.</em> &mdash; for example 833,3 or 833,33 are both correct answers</li>
        <li><em>A train is moving at a speed of 50 km/h. How many kilometers will it travel in a minute? One significant digit is enough. </em> &mdash; for example 0,8</li>
        <li><em>How many carbon atoms (an integer) does a single molecule of a cyclopentano-perhydrophenanthrene contain?</em> &mdash; the answer is 17 &mdash; 17,0001 is a wrong answer</li>
    </ul>
</li>
<li>The competition will consist of a large spectrum of physics problems. Some of them will be very easy and some of them really hard. Therefore, different problems will be worth different amounts of points. The easier problems will be in the so-called <em>Hurry-up</em> series. However, you will have only a limited amount of time to solve them.</li>
</ul>

<h2 id="system">Rules and the scoring system</h2>
<ul>
    <li>
        The competition consists of three parts (the times are in the UTC+1 time zone):
        <ul>
            <li>First part: 17:00 to 18:30.</li>
            <li>Second part: 18:30 to 20:00.</li>
            <li><em>Hurry-up</em> part: 18:00 to 18:30.</li>
        </ul>
    </li>
    <li>The competition will end at 20:00 (3 hours after it began).</li>
    <li>In the first part, each team will be given 7 problems. Once a team solves a problem, it will gain an access to the next problem.</li>
    <li>Teams are awarded points for answering problems correctly. Every problem specifies a maximum amount of points a team can get by solving it. You can submit an answer to a problem as many times as you wish. However, you get the maximum amount of points only if you answer correctly the first time. If you need one more try, you will only gain 0.6 times the maximum number of points. If you need three attempts, you will get 0.4 times the maximum and if four, it is 0.2 times the maximum. However, no matter how many times you try to answer a problem, you will always get at least one point. The amount of points you get is always rounded up.
    </li>
    <li>If you answer incorrectly, your team will be disabled to submit any more answers in the particular group for one minute.</li>
    <li>Second part is essentially the same as the first part. However, teams will have the opportunity not to answer a given problem and to get an access to another problem instead. This action will be penalised by one point.</li>
    <li>If two teams happen to end up with the same number of points, the team who needed a shorter time to solve their last problem will be considered better.</li>
</ul>
<h3>Hurry-up</h3>
<ul>
    <li>An hour after the beginning of the competition, teams will be enabled to answer the problems in the so-called <em>Hurry-up</em> series.</li>
    <li>Teams can submit answers to these problems only during a period of 30 minutes. In this time, you are free to submit answers to the problems from the first part as well.</li>
    <li>The problems are divided into three groups according to their topic. When the Hurry-up series is activated, teams are given one problem from each of these groups. Correctly answering a problem will grant you access to the next problem in the same group.</li>
    <li>If you correctly answer three problems so that each of them is from a different group, and they all have the same sequence number in the corresponding group, you will be given a bonus. This bonus is equal to the number of points you received for solving this triplet of problems.</li>
    <li>If you answer a problem from the <em>Hurry-up</em> series incorrectly, the possible amount of points you can get for this particular problem decreases by one. Therefore, unlike the problems in the first/second part, you can get zero points for a problem in the <em>Hurry-up</em> series.</li>
</ul>

</ul>

<h2 id="equipment">What do I need to participate?</h2>
<ul>
    <li>An access to the Internet (the speed of your connection should not matter). More then one device with an access to the Internet is an advantage but it is not neccessary. You are allowed to use the Internet as a source of information that can help you solve the problems.</li>
    <li>Printer is not neccessary but it might be helpful.</li>
    <li>Papers, pens, literature, calculators&hellip;</li>
    <li>Snacks.</li>
    <li>Team mascot.</li>
</ul>

<h2 id="advices">Tips</h2>
<ul>
    <li>Having more people in your team is an advantage. Therefore, we recommend that you have all five positions filled.</li>
    <li>It is important to decide on a strategy to attack the problems. What problems can you do fast? Is it better to work as a team or to divide the work among individual members? Who decides what individual members work on? You will have a lot of problems available during the competition so it is an advantage to know how to approach them as a team beforehand.</li>
    <li> During the competition you will be able to see how other teams are doing as well as the statistics of each problem. Use this information to figure out what problems might be easy or hard.</li>
</ul>
{/block}
{block #subnavigation}
<ul class="nav">
    <li><a href="#participation">Basic information</a></li>
    <li><a href="#tasks">Problems</a></li>
    <li><a href="#system">Rules and the scoring system </a></li>
    <li><a href="#equipment">What do I need to participate?</a></li>
    <li><a href="#advices">Tips</a></li>
</ul>
{/block}

