{*{cache "results"}*}
{cache}
{var $teams => $teams->fetchAll()}
{var $score => $score->fetchAssoc("id_team,id_task")}
{var $skips => $skips->fetchAssoc("id_team,id_task")}
{var $bonus => $bonus->fetchAssoc("id_team")}
{var $penality => $penality->fetchAssoc("id_team")}

<div id="score-stats-wrapper">
        <div id="score-left"><table class="score-stats" cellspacing="0">
	{foreach $teams AS $team}
		{if $iterator->getCounter() % 10 == 1}
			<tr>
				<th>#</th>
				<th>{_'Tým'}</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
			</tr>
		{/if}
		{if $iterator->getCounter() % 10 == 1 }
			<tr>
		{else}
			<tr class="line">
		{/if}
			<td>{$iterator->getCounter()}</td>
			<td class="team">{$team->name|truncate:15}</td>
			<td>
				{if !empty($team->score)}
					{$team->score}
				{else}
					0
				{/if}
			</td>
			<td>
				{if isset($bonus[$team->id_team])}
					{$bonus[$team->id_team]->score}
				{else}
					0
				{/if}
			</td>
			<td>
				{if isset($penality[$team->id_team])}
					{$penality[$team->id_team]->score}
				{else}
					0
				{/if}
			</td>
		</tr>
	{/foreach}
	</table></div>
    
        <div id="score-right"><table class="score-stats" cellspacing="0">
	{foreach $teams AS $team}
		{if $iterator->getCounter() % 10 == 1}
			<tr>
				{foreach $tasks AS $task}
                                    <th><del n:tag-if="$task->cancelled" title="{_'Zrušená úloha'}">{$task->code_name}</del></th>
				{/foreach}
			</tr>
		{/if}
		{if $iterator->getCounter() % 10 == 1 }
			<tr>
		{else}
			<tr class="line">
		{/if}
			{foreach $tasks AS $task}
                                {if $task->cancelled}
                                        <td class="empty" title="{_'Zrušená úloha'}">&nbsp;</td>
				{elseif isset($skips[$team->id_team]) && isset($skips[$team->id_team][$task->id_task])}
					<td class="skipped">S</td>
                                {elseif !isset($score[$team->id_team]) || !isset($score[$team->id_team][$task->id_task]) || $score[$team->id_team][$task->id_task]->inserted == NULL}
                                        <td class="empty">X</td>
				{else}
					<td class="done">{$score[$team->id_team][$task->id_task]->score}</td>
				{/if}
			{/foreach}
		</tr>
	{/foreach}
            </table></div>
</div>
{/cache}