{*{cache "results"}*}
{cache}
{var $teams => $teams->fetchAll()}
{var $score => $score->fetchAssoc("id_team,id_task")}
{var $skips => $skips->fetchAssoc("id_team,id_task")}
{var $bonus => $bonus->fetchAssoc("id_team")}
{var $penality => $penality->fetchAssoc("id_team")}

<div id="score-stats-wrapper">
        <div id="score-left"><table class="score-stats" cellspacing="0">
	{foreach $teams AS $team}
		{if $iterator->getCounter() % 10 == 1}
			<tr>
				<th>#</th>
				<th>{_'Tým'}</th>
				<th>&sum;</th>
				<th>+</th>
				<th>-</th>
			</tr>
		{/if}
		{if $iterator->getCounter() % 10 == 1 }
			<tr {if $team->activity == 0}class="text-muted"{/if}>
		{else}
			<tr class="line{if $team->activity == 0} text-muted{/if}">
		{/if}
			<td>{$iterator->getCounter()}</td>
                        <td class="team" title="{$team->name}, {$categories[$team->category]}">{$team->name|truncate:15|replace:' ':' '}</td>{* Unicode non-breaking space*}
			<td>
				{if !empty($team->score)}
					{$team->score}
				{else}
					0
				{/if}
			</td>
			<td>
				{if isset($bonus[$team->id_team])}
					{$bonus[$team->id_team]->score}
				{else}
					0
				{/if}
			</td>
			<td>
				{if isset($penality[$team->id_team])}
					{$penality[$team->id_team]->score}
				{else}
					0
				{/if}
			</td>
		</tr>
	{/foreach}
	</table></div>
    
        <div id="score-right"><table class="score-stats" cellspacing="0">
	{foreach $teams AS $team}
		{if $iterator->getCounter() % 10 == 1}
			<tr>
				{foreach $tasks AS $task}
                                    <th n:if="!$task->cancelled" title="{$task|i18n:'name',$lang}">{$task->code_name}</th>
				{/foreach}
			</tr>
		{/if}
		{if $iterator->getCounter() % 10 == 1 }
			<tr {if $team->activity == 0}class="inactive"{/if}>
		{else}
			<tr class="line{if $team->activity == 0} inactive{/if}">
		{/if}
			{foreach $tasks AS $task}
                                {if $task->cancelled}
                                        {*<td class="empty" title="{_'Zrušená úloha'}">&nbsp;</td>*}
				{elseif isset($skips[$team->id_team]) && isset($skips[$team->id_team][$task->id_task])}
					<td class="skipped" title="{$skips[$team->id_team][$task->id_task]->inserted}">S</td>
                                {elseif !isset($score[$team->id_team]) || !isset($score[$team->id_team][$task->id_task]) || $score[$team->id_team][$task->id_task]->inserted == NULL}
                                        <td class="empty">X</td>
				{elseif $score[$team->id_team][$task->id_task]->score == $task->points}
					<td class="done full" title="{$score[$team->id_team][$task->id_task]->inserted}">{$score[$team->id_team][$task->id_task]->score}</td>
                                {else}
					<td class="done" title="{$score[$team->id_team][$task->id_task]->inserted}">{$score[$team->id_team][$task->id_task]->score}</td>
				{/if}                                
			{/foreach}
		</tr>
	{/foreach}
            </table></div>
</div>
{/cache}
