{extends layout.phtml}

{block #subcontent}

{*{cache "problems/$id_team", "problems"}*}
{? Interlos::tasks()->updateCounter($id_team, true)}

<p>{_'K dispozici máte zadání těchto úloh dle podmínek v zadání:'}</p>
<h3>{_'Nevyřešené'}</h3>
{if count($unsolvedTasks) == 0}
<p>{_'Žádné úlohy.'}</p>
{else}
<ul>
    {foreach $unsolvedTasks as $task}
    {block task}
    <li><strong>{$task->code_name}</strong>&nbsp;{$task|i18n:'name',$lang} ({$task->points} b.)
        <ul><li>
            {foreach $mirrors as $mirror}
            <a href="{$mirror}{$task|i18n:'filename',$lang}">Mirror {$iterator->getCounter()}</a>{if !$iterator->isLast()}, {/if}
            {/foreach}
            </li>
        </ul>
    </li>
    {/block}
    {/foreach}
</ul>
{/if}

<h3>{_'Vyřešené'}</h3>
{if count($solvedTasks) == 0}
<p>{_'Žádné úlohy.'}</p>
{else}
<ul>
    {foreach $solvedTasks as $task}
    {include #task}
    {/foreach}
</ul>

<h3>{_'Přeskočené'}</h3>
{if count($solvedTasks) == 0}
<p>{_'Žádné úlohy.'}</p>
{else}
<ul>
    {foreach $skippedTasks as $task}
    {include #task}
    {/foreach}
</ul>
{/if}
{/if}
{*{/cache}*}
<p>
	{_'Kdykoliv je v zadání uvedeno více alternativních webových adres, obsahují všechny adresy stejnou informaci a jsou uvedeny pouze pro zálohu (nikdy tedy není žádná úmyslně skrytá informace v rozdílech mezi verzemi).'}
</p>
{*<p>
	V případě výpadku serveru, na kterém běží systém hry (což se nám stalo loni, ovšem pevně věříme, že letos se to již nestane), budou vystaveny "krizové informace" na následující stránce:
	<a href="http://www.fi.muni.cz/~xpelanek/interlos2/">http://www.fi.muni.cz/~xpelanek/interlos2/</a>
</p>*}
{!_'
<p>
	Na této stránce se také případně objeví zmínka o upřesnění k zadání/opravy chyb.
        Podrobnosti budou v diskusi.
</p>
<p>
	A ještě několik rad:
</p>
<ul>
	<li>Přečtěte si před hrou ještě jednou pravidla, ať máte jasno v bodování.</li>
        <li>Věnujte pozornost sekci &bdquo;rady&ldquo; v pravidlech.</li>
</ul>'}
{*<p>
    Budeme rádi, když nám po soutěži vyplníte <a href="https://docs.google.com/spreadsheet/viewform?pli=1&formkey=dFFzVWpLQ3pGdEFQczNZV1hKS2NwQWc6MQ#gid=0">anketu</a>.
</p>*}

{/block}
