{extends layout.phtml}

{block #subcontent}
<p>K dispozici máte zadání těchto úloh dle podmínek v zadání:</p>

{if count($tasks) == 0}
<p>Žádné úlohy.</p>
{else}
<ul>
    {foreach $tasks as $task}
    <li><strong>{$task->code_name}</strong>&nbsp;{$task->name}
        <ul>
            {foreach $mirrors as $mirror}
            <li><a href="{$mirror}{$task->filename}">{$mirror}{$task->filename}</a></li>
            {/foreach}
        </ul>
    </li>
    {/foreach}
</ul>
{/if}

<p>
	Kdykoliv je v zadání uvedeno více alternativních webových adres, obsahují všechny adresy stejnou informaci a jsou uvedeny pouze pro zálohu (nikdy tedy není žádná úmyslně skrytá informace v rozdílech mezi verzemi).
</p>
{*<p>
	V případě výpadku serveru, na kterém běží systém hry (což se nám stalo loni, ovšem pevně věříme, že letos se to již nestane), budou vystaveny "krizové informace" na následující stránce:
	<a href="http://www.fi.muni.cz/~xpelanek/interlos2/">http://www.fi.muni.cz/~xpelanek/interlos2/</a>
</p>*}

<p>
	Na této stránce se také případně objeví upřesnění k zadání / opravy chyb (opět doufáme a věříme, že ani jedno nebude potřeba). Oznámení tohoto typu se současně objeví také na chatu na stránkách hry.
</p>
<p>
	A ještě několik rad:
</p>
<ul>
	<li>Přečtěte si před hrou ještě jednou pravidla, ať máte jasno v bodování.</li>
        <li>Věnujte pozornost sekci &bdquo;rady&ldquo; v pravidlech.</li>
</ul>
{/block}