{extends ../layout.phtml}

{block #content}
<div id="submenu">
	<ul>
		<li><a href="{plink Game:default}" title="{_'Zadání'}">{_'Zadání'}</a></li>
		{if  Interlos::isGameActive()}
			<li><a href="{plink Game:answer}" title="{_'Odevzdat řešení'}">{_'Odevzdat řešení'}</a></li>
                        <li><a href="{plink Game:skip}" title="{_'Přeskočit úkol'}">{_'Přeskočit úkol'}</a></li>
		{/if}
		{if Interlos::isGameEnd()}
			<li>
				<a href="{$baseUri}download/2013-1/ulohy/reseni.{$lang}.pdf">{_'Řešení'}</a>
			</li>
		{/if}
		<li><a href="{plink Game:history}" title="Historie">{_'Historie'}</a></li>
	</ul>
</div>
<div id="subcontent">
	{block #subcontent}
	{/block}
</div>
{/block}
