{extends ../layout.phtml}
{block #bigcontent}

<table class="table table-condensed table-striped small">
		<thead>
			<th>#</th>
			<th>name</th>
			<th>worst</th>
			<th>best</th>
			<th>correct</th>
			<th>incorrect</th>
                        <th>skipped</th>
		</thead>
			<tr class="" >
				<td>FoL1</td>
				<td>thoughtful</td>
				<td>19:43:37</td>
				<td>17:02:54</td>
				<td>125</td>
				<td>183</td>
                                <td>8</td>
			</tr>
			<tr class="" >
				<td>FoL2</td>
				<td>Ded Moroz</td>
				<td>19:55:42</td>
				<td>17:01:05</td>
				<td>141</td>
				<td>79</td>
                                <td>6</td>
			</tr>
			<tr class="" >
				<td>FoL3</td>
				<td>fiat nox</td>
				<td>19:56:22</td>
				<td>17:04:29</td>
				<td>103</td>
				<td>344</td>
                                <td>14</td>
			</tr>
			<tr class="" >
				<td>FoL4</td>
				<td>the runnier, the better</td>
				<td>19:57:13</td>
				<td>17:06:15</td>
				<td>117</td>
				<td>223</td>
                                <td>11</td>
			</tr>
			<tr class="" >
				<td>FoL5</td>
				<td>brake failure</td>
				<td>19:55:32</td>
				<td>17:02:44</td>
				<td>135</td>
				<td>330</td>
                                <td>3</td>
			</tr>
			<tr class="" >
				<td>FoL6</td>
				<td>fungus librariensis</td>
				<td>19:40:01</td>
				<td>17:02:37</td>
				<td>123</td>
				<td>211</td>
                                <td>9</td>
			</tr>
			<tr class="" >
				<td>FoL7</td>
				<td>server not found</td>
				<td>19:59:09</td>
				<td>17:08:31</td>
				<td>73</td>
				<td>271</td>
                                <td>17</td>
			</tr>
			<tr class="" >
				<td>FoL8</td>
				<td>Archimedes drowned</td>
				<td>19:59:33</td>
				<td>17:16:50</td>
				<td>85</td>
				<td>305</td>
                                <td>13</td>
			</tr>
			<tr class="" >
				<td>FoL9</td>
				<td>carriage on a blind track</td>
				<td>19:59:14</td>
				<td>17:10:03</td>
				<td>107</td>
				<td>300</td>
                                <td>6</td>
			</tr>
			<tr class="" >
				<td>FoL10</td>
				<td>driving in rain</td>
				<td>19:54:14</td>
				<td>17:28:36</td>
				<td>49</td>
				<td>396</td>
                                <td>14</td>
			</tr>
			<tr class="" >
				<td>FoL11</td>
				<td>on your own drive</td>
				<td>19:59:54</td>
				<td>17:23:50</td>
				<td>77</td>
				<td>159</td>
                                <td>9</td>
			</tr>
			<tr class="" >
				<td>FoL12</td>
				<td>the most important letter&#039;s centre of mass</td>
				<td>19:38:24</td>
				<td>17:13:55</td>
				<td>110</td>
				<td>92</td>
                                <td>2</td>
			</tr>
			<tr class="" >
				<td>FoL13</td>
				<td>sulphuring the barrels</td>
				<td>19:58:30</td>
				<td>17:24:39</td>
				<td>57</td>
				<td>213</td>
                                <td>9</td>
			</tr>
			<tr class="" >
				<td>FoL14</td>
				<td>to jump, or not to jump</td>
				<td>19:53:20</td>
				<td>17:18:48</td>
				<td>88</td>
				<td>147</td>
                                <td>4</td>
			</tr>
			<tr class="" >
				<td>FoL15</td>
				<td>tea at five</td>
				<td>19:48:58</td>
				<td>17:25:53</td>
				<td>63</td>
				<td>114</td>
                                <td>6</td>
			</tr>
			<tr class="" >
				<td>FoL16</td>
				<td>scary shopping</td>
				<td>19:59:29</td>
				<td>17:35:21</td>
				<td>88</td>
				<td>61</td>
                                <td>2</td>
			</tr>
			<tr class="" >
				<td>FoL17</td>
				<td>feed a castle</td>
				<td>19:54:29</td>
				<td>17:45:31</td>
				<td>41</td>
				<td>58</td>
                                <td>7</td>
			</tr>
			<tr class="" >
				<td>FoL18</td>
				<td>bullet</td>
				<td>19:58:52</td>
				<td>17:42:05</td>
				<td>60</td>
				<td>51</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL19</td>
				<td>watermelon</td>
				<td>19:58:56</td>
				<td>17:40:40</td>
				<td>66</td>
				<td>95</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL20</td>
				<td>a superconducting one</td>
				<td>19:57:45</td>
				<td>17:51:45</td>
				<td>35</td>
				<td>110</td>
                                <td>2</td>
			</tr>
			<tr class="" >
				<td>FoL21</td>
				<td>buoyant swings with a pulley</td>
				<td>19:59:56</td>
				<td>18:13:45</td>
				<td>22</td>
				<td>89</td>
                                <td>5</td>
			</tr>
			<tr class="" >
				<td>FoL22</td>
				<td>on the head</td>
				<td>19:56:53</td>
				<td>17:48:15</td>
				<td>43</td>
				<td>67</td>
                                <td>2</td>
			</tr>
			<tr class="" >
				<td>FoL23</td>
				<td>an infinite circuit</td>
				<td>19:59:51</td>
				<td>17:48:41</td>
				<td>43</td>
				<td>37</td>
                                <td>2</td>
			</tr>
			<tr class="" >
				<td>FoL24</td>
				<td>bowling with a physicist</td>
				<td>19:59:32</td>
				<td>17:53:45</td>
				<td>16</td>
				<td>61</td>
                                <td>2</td>
			</tr>
			<tr class="" >
				<td>FoL25</td>
				<td>waves and wavelets</td>
				<td>19:58:39</td>
				<td>17:59:31</td>
				<td>18</td>
				<td>48</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL26</td>
				<td>rolling cylinder</td>
				<td>19:53:42</td>
				<td>17:57:07</td>
				<td>33</td>
				<td>20</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL27</td>
				<td>Zdeněk&#039;s sphere</td>
				<td>19:57:02</td>
				<td>18:02:05</td>
				<td>34</td>
				<td>16</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL28</td>
				<td>energetic surface</td>
				<td>19:59:26</td>
				<td>18:06:55</td>
				<td>26</td>
				<td>5</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL29</td>
				<td>pyramid&#039;s circuits vol. 2</td>
				<td>19:50:51</td>
				<td>18:36:23</td>
				<td>7</td>
				<td>22</td>
                                <td>2</td>
			</tr>
			<tr class="" >
				<td>FoL30</td>
				<td>gassed joules</td>
				<td>19:56:22</td>
				<td>18:51:09</td>
				<td>13</td>
				<td>7</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL31</td>
				<td>elusive lens</td>
				<td>19:59:41</td>
				<td>18:41:51</td>
				<td>16</td>
				<td>22</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL32</td>
				<td>playing in the field</td>
				<td>19:59:51</td>
				<td>18:49:28</td>
				<td>16</td>
				<td>7</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL33</td>
				<td>planet Fykosia</td>
				<td>19:59:21</td>
				<td>18:49:47</td>
				<td>13</td>
				<td>5</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL34</td>
				<td>feather-light</td>
				<td>19:59:21</td>
				<td>18:56:10</td>
				<td>8</td>
				<td>4</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL35</td>
				<td>an accelerated one</td>
				<td>19:56:52</td>
				<td>18:58:29</td>
				<td>11</td>
				<td>4</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL36</td>
				<td>resistance upside down</td>
				<td>19:36:38</td>
				<td>19:15:01</td>
				<td>6</td>
				<td>6</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL37</td>
				<td>nomen omen</td>
				<td>19:58:01</td>
				<td>19:06:02</td>
				<td>9</td>
				<td>7</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL38</td>
				<td>pendulum</td>
				<td>19:47:53</td>
				<td>19:24:57</td>
				<td>4</td>
				<td>8</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL39</td>
				<td>magnetic focusing</td>
				<td>19:52:46</td>
				<td>19:37:56</td>
				<td>4</td>
				<td>6</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL40</td>
				<td>slingshooty</td>
				<td>19:54:51</td>
				<td>19:17:31</td>
				<td>6</td>
				<td>0</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL41</td>
				<td>little gifts</td>
				<td>19:58:12</td>
				<td>19:39:24</td>
				<td>2</td>
				<td>4</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL42</td>
				<td>van de Graaff</td>
				<td></td>
				<td></td>
				<td>0</td>
				<td>5</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>M1</td>
				<td>electrical shopping cart</td>
				<td>18:29:26</td>
				<td>18:03:13</td>
				<td>68</td>
				<td>157</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>M2</td>
				<td>Náry&#039;s academic quarter</td>
				<td>18:29:44</td>
				<td>18:06:41</td>
				<td>46</td>
				<td>36</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>M3</td>
				<td>truly solid lecture notes</td>
				<td>18:29:13</td>
				<td>18:09:48</td>
				<td>22</td>
				<td>23</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>M4</td>
				<td>all in vane</td>
				<td>18:29:37</td>
				<td>18:14:46</td>
				<td>13</td>
				<td>2</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>E1</td>
				<td>the long one and the wide one</td>
				<td>18:29:54</td>
				<td>18:01:21</td>
				<td>118</td>
				<td>120</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>E2</td>
				<td>one, two, three,...</td>
				<td>18:29:44</td>
				<td>18:06:49</td>
				<td>55</td>
				<td>31</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>E3</td>
				<td>experimental afternoon</td>
				<td>18:29:32</td>
				<td>18:12:52</td>
				<td>26</td>
				<td>11</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>E4</td>
				<td>pyramid&#039;s circuits</td>
				<td>18:29:47</td>
				<td>18:15:15</td>
				<td>9</td>
				<td>4</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>X1</td>
				<td>uncertain bacteria</td>
				<td>18:29:02</td>
				<td>18:04:47</td>
				<td>53</td>
				<td>74</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>X2</td>
				<td>a lecture on relativity</td>
				<td>18:27:41</td>
				<td>18:10:33</td>
				<td>22</td>
				<td>49</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>X3</td>
				<td>hot grating</td>
				<td>18:28:35</td>
				<td>18:15:58</td>
				<td>5</td>
				<td>3</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>X4</td>
				<td>beta decay</td>
				<td>18:24:56</td>
				<td>18:24:56</td>
				<td>1</td>
				<td>2</td>
                                <td>0</td>
			</tr>
	</table>
