{extends ../layout.phtml}
{block #content}
<p>Šedé jsou týmy, jež neprojevily během hry aktivitu.</p>
	<h2 id="hs_a">Středoškoláci A</h2>
	<table class="table table-condensed table-striped">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class=" ">
				<td>1</td>
				<td>Okarusov blesk</td>
				<td>
						134
				</td>
				<td>
						25
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>2</td>
				<td>Gympláci</td>
				<td>
						86
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>3</td>
				<td>Gymik+Tonda</td>
				<td>
						84
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>4</td>
				<td>Grupa Jedákov Horaliek</td>
				<td>
						61
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>5</td>
				<td>Zkrocený kůň</td>
				<td>
						57
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>6</td>
				<td>GCL</td>
				<td>
						53
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>7</td>
				<td>Bikonkavne piskoty</td>
				<td>
						49
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>8</td>
				<td>Mňága</td>
				<td>
						46
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class=" ">
				<td>9</td>
				<td>Balistické střely</td>
				<td>
						35
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>10</td>
				<td>Fialové hrnce</td>
				<td>
						28
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>11</td>
				<td>Gymnázium Ústí nad Orlicí</td>
				<td>
						27
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>12</td>
				<td>Gymtri3</td>
				<td>
						27
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>13</td>
				<td>!SVETLOM 2</td>
				<td>
						27
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>14</td>
				<td>All Star</td>
				<td>
						22
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>15</td>
				<td>Like the πrates!</td>
				<td>
						20
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>16</td>
				<td>Hatalom</td>
				<td>
						20
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>17</td>
				<td>Chemici</td>
				<td>
						19
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>18</td>
				<td>Stěrači</td>
				<td>
						17
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class=" ">
				<td>19</td>
				<td>Posse Rem Esse</td>
				<td>
						16
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>20</td>
				<td>PuGy</td>
				<td>
						16
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>21</td>
				<td>Mračno</td>
				<td>
						16
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>22</td>
				<td>Andiho banda</td>
				<td>
						11
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>23</td>
				<td>ACDC</td>
				<td>
						11
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>24</td>
				<td>Skippy</td>
				<td>
						5
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>25</td>
				<td>GymKadaŇ</td>
				<td>
						2
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>26</td>
				<td>Bylináři</td>
				<td>
						-1
				</td>
				<td>
						0
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class=" text-muted">
				<td>27</td>
				<td>Nutella</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>28</td>
				<td>Ups</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
	</table>
	<h2 id="hs_b">Středoškoláci B</h2>
	<table class="table table-condensed table-striped">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class=" ">
				<td>1</td>
				<td>Ešte ďalej</td>
				<td>
						78
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>2</td>
				<td>Gymji PRO team 1337</td>
				<td>
						57
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>3</td>
				<td>alea</td>
				<td>
						47
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>4</td>
				<td>Budulínci</td>
				<td>
						41
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>5</td>
				<td>Master Minds</td>
				<td>
						34
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>6</td>
				<td>Perpetuálně mobilní skvadra</td>
				<td>
						34
				</td>
				<td>
						0
				</td>
				<td>
						5
				</td>
			</tr>
			<tr class=" ">
				<td>7</td>
				<td>G</td>
				<td>
						29
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>8</td>
				<td>GymBos8</td>
				<td>
						24
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>9</td>
				<td>dašák</td>
				<td>
						23
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>10</td>
				<td>007</td>
				<td>
						18
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>11</td>
				<td>Bohumír gang</td>
				<td>
						17
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>12</td>
				<td>Vaflicky</td>
				<td>
						17
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>13</td>
				<td>GIO</td>
				<td>
						16
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>14</td>
				<td>Tí najkrajší</td>
				<td>
						16
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>15</td>
				<td>Okena s.r.o</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>16</td>
				<td>Vektor</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>17</td>
				<td>GangnamStyle</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>18</td>
				<td>Gymtri2</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>19</td>
				<td>MiPeVi Team</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>20</td>
				<td>Just Me</td>
				<td>
						10
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>21</td>
				<td>GymBos</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>22</td>
				<td>Atomové koule</td>
				<td>
						1
				</td>
				<td>
						0
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class=" ">
				<td>23</td>
				<td>Béčkaři</td>
				<td>
						1
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>24</td>
				<td>Rubikon</td>
				<td>
						1
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>25</td>
				<td>BigyTime</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>26</td>
				<td>Einsteinovi borci</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>27</td>
				<td>Chyba Matrixu</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>28</td>
				<td>mAthVENGERS</td>
				<td>
						-1
				</td>
				<td>
						0
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class=" text-muted">
				<td>29</td>
				<td>Cabbage</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>30</td>
				<td>Lebečníci</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>31</td>
				<td>m.raszyk</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>32</td>
				<td>RaKuKaVoLi</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>33</td>
				<td>Von Neumann&#039;s crushers</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
	</table>
	<h2 id="hs_c">Středoškoláci C</h2>
	<table class="table table-condensed table-striped">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class=" ">
				<td>1</td>
				<td>Gymtri1</td>
				<td>
						29
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>2</td>
				<td>Hejčín 3,884</td>
				<td>
						25
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>3</td>
				<td>Gočovskí Junáci z Hôr</td>
				<td>
						23
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>4</td>
				<td>Radek Chmelař</td>
				<td>
						18
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>5</td>
				<td>Gamča Chewers</td>
				<td>
						18
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>6</td>
				<td>Ne*TU!sIm</td>
				<td>
						18
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>7</td>
				<td>wigymos</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>8</td>
				<td>Gečkári</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>9</td>
				<td>Gymlovo</td>
				<td>
						13
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>10</td>
				<td>E-lita gph</td>
				<td>
						12
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>11</td>
				<td>Koalice flegmatických tyranosaurů</td>
				<td>
						11
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>12</td>
				<td>Schrödingerova koťátka</td>
				<td>
						10
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class=" ">
				<td>13</td>
				<td>Loupáci</td>
				<td>
						9
				</td>
				<td>
						0
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class="even ">
				<td>14</td>
				<td>HBTeam</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class=" ">
				<td>15</td>
				<td>Exodus</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>16</td>
				<td>Športovci bez chyby</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>17</td>
				<td>Bobríci</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class="even ">
				<td>18</td>
				<td>GUHTeam</td>
				<td>
						5
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>19</td>
				<td>Hyperaktivní lenochodi</td>
				<td>
						5
				</td>
				<td>
						0
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class="even ">
				<td>20</td>
				<td>Ledk(G)y</td>
				<td>
						4
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>21</td>
				<td>NoobCakes</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>22</td>
				<td>Pařížská elita</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>23</td>
				<td>MG - Plzeň</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>24</td>
				<td>Syntax Error</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class=" ">
				<td>25</td>
				<td>E = mc²</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class="even ">
				<td>26</td>
				<td>Hejčín4</td>
				<td>
						2
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>27</td>
				<td>Hadi na kole</td>
				<td>
						2
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>28</td>
				<td>Ačkári</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>29</td>
				<td>Ajťáci</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>30</td>
				<td>Broňovi mazánci</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>31</td>
				<td>Frantíci</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>32</td>
				<td>GPH A-čka</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>33</td>
				<td>HD</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>34</td>
				<td>Chytří z Vodňan</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>35</td>
				<td>Kameni</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>36</td>
				<td>Kráťovy děcka</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>37</td>
				<td>Patková- Sekunda</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>38</td>
				<td>PrimeNumbers</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>39</td>
				<td>Sirloin steak</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>40</td>
				<td>Zachyho buchtičky</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>41</td>
				<td>00101102</td>
				<td>
						-1
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>42</td>
				<td>Blinking Bulb</td>
				<td>
						-3
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class=" ">
				<td>43</td>
				<td>Peťové</td>
				<td>
						-3
				</td>
				<td>
						0
				</td>
				<td>
						6
				</td>
			</tr>
			<tr class="even ">
				<td>44</td>
				<td>HaTeBaSiMo</td>
				<td>
						-7
				</td>
				<td>
						0
				</td>
				<td>
						7
				</td>
			</tr>
			<tr class=" ">
				<td>45</td>
				<td>Procira</td>
				<td>
						-24
				</td>
				<td>
						0
				</td>
				<td>
						24
				</td>
			</tr>
			<tr class="even text-muted">
				<td>46</td>
				<td>dd</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>47</td>
				<td>Nutcase team</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>48</td>
				<td>Osmáci</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>49</td>
				<td>pplo</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>50</td>
				<td>Tým</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>51</td>
				<td>ZŠ Dělnická</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
	</table>
	<h2 id="abroad">Zahraniční SŠ</h2>
	<table class="table table-condensed table-striped">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class=" ">
				<td>1</td>
				<td>bieber</td>
				<td>
						94
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>2</td>
				<td>terserah</td>
				<td>
						81
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class=" ">
				<td>3</td>
				<td>NSAMF-BiH</td>
				<td>
						80
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>4</td>
				<td>TALENTOS SABROSONES</td>
				<td>
						60
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>5</td>
				<td>Electrostatic</td>
				<td>
						42
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>6</td>
				<td>LOS DOTEROS</td>
				<td>
						41
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>7</td>
				<td>Yognauts</td>
				<td>
						38
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>8</td>
				<td>Passion for life</td>
				<td>
						31
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>9</td>
				<td>Uniformiter Disformis</td>
				<td>
						31
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>10</td>
				<td>Magical 5</td>
				<td>
						28
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>11</td>
				<td>Fisicatimbó</td>
				<td>
						26
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>12</td>
				<td>Caixa de Schrödinger</td>
				<td>
						25
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>13</td>
				<td>Siddharth Mohan</td>
				<td>
						24
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class="even ">
				<td>14</td>
				<td>0 Kelvin</td>
				<td>
						23
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>15</td>
				<td>Kit Química 500</td>
				<td>
						22
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>16</td>
				<td>HIVAK</td>
				<td>
						22
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>17</td>
				<td>Lord of physics</td>
				<td>
						19
				</td>
				<td>
						0
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class="even ">
				<td>18</td>
				<td>RESERVA 5-A</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>19</td>
				<td>AUTOBOTS</td>
				<td>
						13
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>20</td>
				<td>protons</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>21</td>
				<td>Fizikai</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>22</td>
				<td>Rietavas</td>
				<td>
						5
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>23</td>
				<td>Enginers</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>24</td>
				<td>Fire</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>25</td>
				<td>Linksmučiai</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>26</td>
				<td>Mission</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>27</td>
				<td>SJBísica</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>28</td>
				<td>Darth Newton</td>
				<td>
						-1
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" text-muted">
				<td>29</td>
				<td>A</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>30</td>
				<td>Action Reaction</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>31</td>
				<td>bla</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>32</td>
				<td>Bonde do Obina</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>33</td>
				<td>D</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>34</td>
				<td>eigen vector</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>35</td>
				<td>Entropia Zero</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>36</td>
				<td>Hadron</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>37</td>
				<td>Hobbit</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>38</td>
				<td>IME/ITA</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>39</td>
				<td>MehboobSultana</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>40</td>
				<td>Murback</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>41</td>
				<td>O&amp;M</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>42</td>
				<td>Physics Elites</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>43</td>
				<td>Quanta</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>44</td>
				<td>rio_de_janeiro</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>45</td>
				<td>Schrodinger&#039;s Laureates</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>46</td>
				<td>Ts team</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>47</td>
				<td>Yad neerg</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
	</table>
	<h2 id="open">Open</h2>
	<table class="table table-condensed table-striped">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class=" ">
				<td>1</td>
				<td>kTP^2/(MJ) = MaKaJ ToPře</td>
				<td>
						159
				</td>
				<td>
						18
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>2</td>
				<td>Veterani</td>
				<td>
						139
				</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>3</td>
				<td>ὅπερ ἔδει δεῖξαι</td>
				<td>
						115
				</td>
				<td>
						8
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>4</td>
				<td>Čučoriedie rozmanité</td>
				<td>
						101
				</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>5</td>
				<td>Sinergy</td>
				<td>
						90
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>6</td>
				<td>najebongo_wężowniki</td>
				<td>
						84
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>7</td>
				<td>I want to be the part of it</td>
				<td>
						77
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>8</td>
				<td>symmetrysoul</td>
				<td>
						74
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>9</td>
				<td>Hustá podmnožina</td>
				<td>
						62
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>10</td>
				<td>Corpus omne perseverare in statu suo quiescendi vel movendi uniformiter in directum, nisi quatenus illud a viribus impressis cogitur statum suum mutar</td>
				<td>
						56
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>11</td>
				<td>p3</td>
				<td>
						52
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>12</td>
				<td>Krávu za vocas</td>
				<td>
						48
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>13</td>
				<td>Casimir Squid Force</td>
				<td>
						38
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>14</td>
				<td>Kobliha</td>
				<td>
						37
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>15</td>
				<td>BBW</td>
				<td>
						31
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>16</td>
				<td>NU physics team</td>
				<td>
						30
				</td>
				<td>
						0
				</td>
				<td>
						7
				</td>
			</tr>
			<tr class=" ">
				<td>17</td>
				<td>Zelený elektron</td>
				<td>
						26
				</td>
				<td>
						0
				</td>
				<td>
						6
				</td>
			</tr>
			<tr class="even ">
				<td>18</td>
				<td>Wolfici</td>
				<td>
						26
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>19</td>
				<td>Fisica un</td>
				<td>
						25
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>20</td>
				<td>e=mc2</td>
				<td>
						24
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>21</td>
				<td>Wow</td>
				<td>
						22
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>22</td>
				<td>Tal.4Ever</td>
				<td>
						22
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>23</td>
				<td>Relatividade Geral</td>
				<td>
						17
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>24</td>
				<td>Elektronai</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>25</td>
				<td>Arabian Falcons</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>26</td>
				<td>Vlk samotář</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>27</td>
				<td>Grupo MYO</td>
				<td>
						2
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>28</td>
				<td>The Cantemir&#039;s</td>
				<td>
						2
				</td>
				<td>
						0
				</td>
				<td>
						9
				</td>
			</tr>
			<tr class=" ">
				<td>29</td>
				<td>Organizers</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>30</td>
				<td>Blbec z Xeenemünde</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>31</td>
				<td>Calculus</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>32</td>
				<td>deden solo</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>33</td>
				<td>Elektronai1</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>34</td>
				<td>Física y yo</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>35</td>
				<td>Islamians</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>36</td>
				<td>JFM</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>37</td>
				<td>knowledge</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>38</td>
				<td>physics matters</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>39</td>
				<td>ptoko</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>40</td>
				<td>Science Rock</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>41</td>
				<td>team93</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>42</td>
				<td>THE BEST*</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>43</td>
				<td>The Cyrcle</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>44</td>
				<td>Tým týmů</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>45</td>
				<td>Yiyiphysics</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
	</table>


{/block}
