<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="content-language" content="cs" />
        <link rel="stylesheet" type="text/css" href="/css/all.css" />
        <link href="/favicon.png" rel="icon" type="image/png" />
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
        <script type="text/javascript" src="http://code.jquery.com/ui/1.8.2/jquery-ui.js"></script>

        <title>
            Online Physics Brawl
        </title>
    </head>

    <body>
        <!-- HEADER -->
        <div id="header">
            <a href="/en/" title="Online Physics Brawl">
                <div class="wrapper">
                    <div id="logo"></div>
                    <h1>Online Physics Brawl</h1>
                </div>
            </a>
        </div>
        <!-- MENU -->
        <div id="menu">
            <div class="wrapper">
                <ul id="team-navigation">
                    <li><a href="/en/default/login">Log in</a></li>
                    <li><a href="/cs/stats/tasks"><img src="/images/icons/cz-icon.png" alt="čeština" title="Přepnout do češtiny"/></a></li>
                </ul>
                <ul id="general-navigation">
                    <li><a href="/en/default/rules" title="Rules">Rules</a></li>
                    <li><a href="/en/default/last-years" title="Recent years">Recent years</a></li>
                    <li><a href="/en/default/chat" title="Forum">Forum</a></li>
                    <li><a href="/en/team/list" title="Teams">Teams</a></li>
                    <li><a href="/en/stats/" title="Statistics">Statistics</a></li>
                </ul>
            </div>
        </div>
        <div class="wrapper">
            <!-- PAGE TITLE -->            <h1>Problem statistics</h1>
            <!-- FLASH MESSAGES -->
<div id="flashes">
</div>            <!-- CONTENT -->
            <div id="content">
                    <div id="submenu">
	<ul>
		<li>
			<a href="/en/stats/" title="Results">Results</a>
			<ul>
                                <li><a href="/en/stats/#hs_a" title="High school students A">High school students A</a></li>
                                <li><a href="/en/stats/#hs_b" title="High school students B">High school students B</a></li>
                                <li><a href="/en/stats/#hs_c" title="High school students C">High school students C</a></li>
                                <li><a href="/en/stats/#abroad" title="High school outside of Czech Republic">High school outside of Czech Republic</a></li>
                                <li><a href="/en/stats/#open" title="Open">Open</a></li>
			</ul>
		</li>
		<li><a href="/en/stats/detail" title="Detailed results">Detailed results</a></li>
		<li><a href="/en/stats/tasks" title="Problem statistics">Problem statistics</a></li>
	</ul>
    </div>
    <div id="subcontent">
	<table id="task-stats" cellspacing="0">
		<thead>
			<th>#</th>
			<th>name</th>
			<th>worst</th>
			<th>best</th>
						<th>correct</th>
			<th>incorrect</th>
                        <th>skipped</th>
		</thead>
			<tr class="" >
				<td>FoL1</td>
				<td>jumping dog</td>
				<td>19:51:17</td>
				<td>17:02:43</td>
				<td>149</td>
				<td>224</td>
                                <td>4</td>
			</tr>
			<tr class="even" >
				<td>FoL2</td>
				<td>source of radiation</td>
				<td>19:59:49</td>
				<td>17:02:20</td>
				<td>105</td>
				<td>154</td>
                                <td>19</td>
			</tr>
			<tr class="" >
				<td>FoL3</td>
				<td>fluctuational</td>
				<td>19:56:06</td>
				<td>17:11:17</td>
				<td>76</td>
				<td>120</td>
                                <td>35</td>
			</tr>
			<tr class="even" >
				<td>FoL4</td>
				<td>czech energetics</td>
				<td>19:48:52</td>
				<td>17:03:58</td>
				<td>139</td>
				<td>181</td>
                                <td>4</td>
			</tr>
			<tr class=" inactive" title="Zrušená úloha">
				<td>FoL5</td>
				<td>fall one</td>
				<td></td>
				<td></td>
				<td>&mdash;</td>
				<td>&mdash;</td>
                                <td>16</td>
			</tr>
			<tr class="even inactive" title="Zrušená úloha">
				<td>FoL6</td>
				<td>choo choo train</td>
				<td></td>
				<td></td>
				<td>&mdash;</td>
				<td>&mdash;</td>
                                <td>0</td>
			</tr>
			<tr class=" inactive" title="Zrušená úloha">
				<td>FoL7</td>
				<td>collision!!!</td>
				<td></td>
				<td></td>
				<td>&mdash;</td>
				<td>&mdash;</td>
                                <td>45</td>
			</tr>
			<tr class="even" >
				<td>FoL8</td>
				<td>semicircular analyzer</td>
				<td>19:42:19</td>
				<td>17:13:04</td>
				<td>60</td>
				<td>41</td>
                                <td>37</td>
			</tr>
			<tr class="" >
				<td>FoL9</td>
				<td>upgrade</td>
				<td>19:59:46</td>
				<td>17:22:08</td>
				<td>58</td>
				<td>234</td>
                                <td>16</td>
			</tr>
			<tr class="even" >
				<td>FoL10</td>
				<td>let there be equality</td>
				<td>19:59:16</td>
				<td>17:35:00</td>
				<td>45</td>
				<td>222</td>
                                <td>18</td>
			</tr>
			<tr class="" >
				<td>FoL11</td>
				<td>apple cider</td>
				<td>19:58:39</td>
				<td>17:35:08</td>
				<td>43</td>
				<td>250</td>
                                <td>10</td>
			</tr>
			<tr class="even" >
				<td>FoL12</td>
				<td>Wien&#039;s filter</td>
				<td>19:55:16</td>
				<td>17:32:00</td>
				<td>63</td>
				<td>9</td>
                                <td>9</td>
			</tr>
			<tr class="" >
				<td>FoL13</td>
				<td>pseudo-ice tea</td>
				<td>19:57:46</td>
				<td>17:39:12</td>
				<td>59</td>
				<td>108</td>
                                <td>7</td>
			</tr>
			<tr class="even" >
				<td>FoL14</td>
				<td>climbing acetone</td>
				<td>19:58:25</td>
				<td>17:48:00</td>
				<td>61</td>
				<td>76</td>
                                <td>4</td>
			</tr>
			<tr class="" >
				<td>FoL15</td>
				<td>the round one</td>
				<td>19:59:57</td>
				<td>17:42:39</td>
				<td>42</td>
				<td>34</td>
                                <td>12</td>
			</tr>
			<tr class="even" >
				<td>FoL16</td>
				<td>the bulb and the capacitor</td>
				<td>19:59:17</td>
				<td>18:00:54</td>
				<td>17</td>
				<td>77</td>
                                <td>9</td>
			</tr>
			<tr class="" >
				<td>FoL17</td>
				<td>the rod on the wires</td>
				<td>19:53:33</td>
				<td>18:22:01</td>
				<td>14</td>
				<td>49</td>
                                <td>8</td>
			</tr>
			<tr class="even" >
				<td>FoL18</td>
				<td>totem</td>
				<td>19:55:40</td>
				<td>17:55:03</td>
				<td>33</td>
				<td>51</td>
                                <td>3</td>
			</tr>
			<tr class="" >
				<td>FoL19</td>
				<td>solar mania</td>
				<td>19:59:10</td>
				<td>18:00:57</td>
				<td>31</td>
				<td>15</td>
                                <td>2</td>
			</tr>
			<tr class="even" >
				<td>FoL20</td>
				<td>a decaying one</td>
				<td>19:57:42</td>
				<td>18:42:40</td>
				<td>19</td>
				<td>28</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL21</td>
				<td>thermo-sphere</td>
				<td>19:56:43</td>
				<td>18:10:21</td>
				<td>26</td>
				<td>15</td>
                                <td>1</td>
			</tr>
			<tr class="even" >
				<td>FoL22</td>
				<td>analogue hydrometer</td>
				<td>19:59:51</td>
				<td>18:52:07</td>
				<td>8</td>
				<td>39</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL23</td>
				<td>pressurized box</td>
				<td>19:55:45</td>
				<td>18:21:17</td>
				<td>17</td>
				<td>24</td>
                                <td>1</td>
			</tr>
			<tr class="even" >
				<td>FoL24</td>
				<td>world champion in high jump</td>
				<td>19:57:21</td>
				<td>18:40:15</td>
				<td>11</td>
				<td>36</td>
                                <td>2</td>
			</tr>
			<tr class="" >
				<td>FoL25</td>
				<td>pulleys</td>
				<td>19:35:05</td>
				<td>19:22:04</td>
				<td>3</td>
				<td>41</td>
                                <td>2</td>
			</tr>
			<tr class="even" >
				<td>FoL26</td>
				<td>boxed light</td>
				<td>19:56:43</td>
				<td>19:05:17</td>
				<td>6</td>
				<td>20</td>
                                <td>2</td>
			</tr>
			<tr class="" >
				<td>FoL27</td>
				<td>enlightened carriage</td>
				<td>19:56:38</td>
				<td>19:05:28</td>
				<td>6</td>
				<td>7</td>
                                <td>1</td>
			</tr>
			<tr class="even" >
				<td>FoL28</td>
				<td>Earth-cylinder</td>
				<td>19:57:46</td>
				<td>19:11:24</td>
				<td>2</td>
				<td>4</td>
                                <td>2</td>
			</tr>
			<tr class="" >
				<td>FoL29</td>
				<td>pass me the hammer</td>
				<td>19:57:08</td>
				<td>19:20:10</td>
				<td>4</td>
				<td>3</td>
                                <td>1</td>
			</tr>
			<tr class="even" >
				<td>FoL30</td>
				<td>a messy one</td>
				<td>19:53:01</td>
				<td>19:53:01</td>
				<td>1</td>
				<td>2</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL31</td>
				<td>valuing the decays</td>
				<td>19:40:24</td>
				<td>19:40:24</td>
				<td>1</td>
				<td>1</td>
                                <td>1</td>
			</tr>
			<tr class="even" >
				<td>FoL32</td>
				<td>Flash</td>
				<td>19:36:57</td>
				<td>19:36:57</td>
				<td>1</td>
				<td>2</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL33</td>
				<td>we need to go deeper</td>
				<td></td>
				<td></td>
				<td>0</td>
				<td>1</td>
                                <td>1</td>
			</tr>
			<tr class="even" >
				<td>FoL34</td>
				<td>little skewer</td>
				<td>19:55:32</td>
				<td>19:55:32</td>
				<td>1</td>
				<td>0</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL35</td>
				<td>tesseract</td>
				<td></td>
				<td></td>
				<td>0</td>
				<td>1</td>
                                <td>1</td>
			</tr>
			<tr class="even" >
				<td>FoL36</td>
				<td>short hands</td>
				<td></td>
				<td></td>
				<td>0</td>
				<td>0</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL37</td>
				<td>resistant Fibonacci</td>
				<td></td>
				<td></td>
				<td>0</td>
				<td>1</td>
                                <td>0</td>
			</tr>
			<tr class="even" >
				<td>M1</td>
				<td>stilettos</td>
				<td>18:29:29</td>
				<td>18:03:28</td>
				<td>110</td>
				<td>154</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>M2</td>
				<td>traffic jam</td>
				<td>18:29:57</td>
				<td>18:07:55</td>
				<td>21</td>
				<td>101</td>
                                <td>0</td>
			</tr>
			<tr class="even" >
				<td>M3</td>
				<td>very slow relativity</td>
				<td>18:28:59</td>
				<td>18:20:12</td>
				<td>5</td>
				<td>18</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>M4</td>
				<td>splash</td>
				<td>18:22:29</td>
				<td>18:22:29</td>
				<td>1</td>
				<td>0</td>
                                <td>0</td>
			</tr>
			<tr class="even" >
				<td>E1</td>
				<td>flash</td>
				<td>18:29:48</td>
				<td>18:06:21</td>
				<td>30</td>
				<td>89</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>E2</td>
				<td>tangled resistances</td>
				<td>18:28:24</td>
				<td>18:08:40</td>
				<td>20</td>
				<td>4</td>
                                <td>0</td>
			</tr>
			<tr class="even" >
				<td>E3</td>
				<td>aberration</td>
				<td>18:29:52</td>
				<td>18:15:18</td>
				<td>5</td>
				<td>3</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>E4</td>
				<td>useless work</td>
				<td>18:29:20</td>
				<td>18:20:55</td>
				<td>3</td>
				<td>0</td>
                                <td>0</td>
			</tr>
			<tr class="even" >
				<td>X1</td>
				<td>let&#039;s spread out</td>
				<td>18:29:20</td>
				<td>18:07:30</td>
				<td>22</td>
				<td>191</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>X2</td>
				<td>heating season</td>
				<td>18:29:55</td>
				<td>18:15:31</td>
				<td>6</td>
				<td>22</td>
                                <td>0</td>
			</tr>
			<tr class="even" >
				<td>X3</td>
				<td>hexagonal sphere</td>
				<td>18:27:51</td>
				<td>18:25:43</td>
				<td>2</td>
				<td>0</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>X4</td>
				<td>firm or springy</td>
				<td></td>
				<td></td>
				<td>0</td>
				<td>0</td>
                                <td>0</td>
			</tr>
	</table>
    </div>

            </div>
        </div>
        <div id="footer"></div>
        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-27814405-2']);
            _gaq.push(['_setDomainName', "online.fyziklani.cz"]);
            _gaq.push(['_setAllowLinker', true]);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script');
                ga.type = 'text/javascript';
                ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(ga, s);
            })();

        </script>

    </body>
</html>
