{extends ../layout.phtml}
{block #content}

<table id="task-stats" cellspacing="0">
		<thead>
			<th>#</th>
			<th>název</th>
			<th>nejhorší</th>
			<th>nejlepší</th>
						<th>správně</th>
			<th>špatně</th>
                        <th>přeskočeno</th>
		</thead>
			<tr>
				<td>FoL1</td>
				<td>závěs</td>
				<td>19:47:37</td>
				<td>17:02:44</td>
								<td>92</td>
				<td>190</td>
                                <td>6</td>
			</tr>
			<tr class="even">
				<td>FoL2</td>
				<td>oběšenci</td>
				<td>19:48:23</td>
				<td>17:10:00</td>
								<td>61</td>
				<td>66</td>
                                <td>18</td>
			</tr>
			<tr>
				<td>FoL3</td>
				<td>mokrá skála</td>
				<td>19:12:01</td>
				<td>17:30:10</td>
								<td>9</td>
				<td>826</td>
                                <td>29</td>
			</tr>
			<tr class="even">
				<td>FoL4</td>
				<td>plynová přepážka</td>
				<td>19:52:29</td>
				<td>17:05:35</td>
								<td>98</td>
				<td>153</td>
                                <td>9</td>
			</tr>
			<tr>
				<td>FoL5</td>
				<td>Pojďme hrát kuličky!</td>
				<td>19:58:17</td>
				<td>17:07:22</td>
								<td>118</td>
				<td>270</td>
                                <td>23</td>
			</tr>
			<tr class="even">
				<td>FoL6</td>
				<td>pruží to</td>
				<td>19:56:21</td>
				<td>17:07:12</td>
								<td>39</td>
				<td>161</td>
                                <td>15</td>
			</tr>
			<tr>
				<td>FoL7</td>
				<td>roztahovačný balón</td>
				<td>19:58:30</td>
				<td>17:09:24</td>
								<td>92</td>
				<td>96</td>
                                <td>7</td>
			</tr>
			<tr class="even">
				<td>FoL8</td>
				<td>odporný hranol</td>
				<td>19:58:20</td>
				<td>17:12:12</td>
								<td>49</td>
				<td>140</td>
                                <td>8</td>
			</tr>
			<tr>
				<td>FoL9</td>
				<td>družice</td>
				<td>19:57:22</td>
				<td>17:21:36</td>
								<td>12</td>
				<td>96</td>
                                <td>0</td>
			</tr>
			<tr class="even">
				<td>FoL10</td>
				<td>smyčka</td>
				<td>19:58:56</td>
				<td>17:36:01</td>
								<td>25</td>
				<td>52</td>
                                <td>6</td>
			</tr>
			<tr>
				<td>FoL11</td>
				<td>ekologický pasivista</td>
				<td>19:55:56</td>
				<td>17:31:23</td>
								<td>25</td>
				<td>102</td>
                                <td>4</td>
			</tr>
			<tr class="even">
				<td>FoL12</td>
				<td>jádro na dietě</td>
				<td>19:59:53</td>
				<td>17:36:21</td>
								<td>27</td>
				<td>30</td>
                                <td>6</td>
			</tr>
			<tr>
				<td>FoL13</td>
				<td>hudba lokomotiv</td>
				<td>19:47:56</td>
				<td>17:46:36</td>
								<td>21</td>
				<td>46</td>
                                <td>2</td>
			</tr>
			<tr class="even">
				<td>FoL14</td>
				<td>kondenzátory v obvodu</td>
				<td>19:52:03</td>
				<td>18:00:48</td>
								<td>21</td>
				<td>23</td>
                                <td>3</td>
			</tr>
			<tr>
				<td>FoL15</td>
				<td>brýle nebo kontaktní čočky</td>
				<td>19:48:41</td>
				<td>17:59:24</td>
								<td>4</td>
				<td>19</td>
                                <td>4</td>
			</tr>
			<tr class="even">
				<td>FoL16</td>
				<td>nadsvětelný elektron </td>
				<td>19:57:34</td>
				<td>18:09:49</td>
								<td>13</td>
				<td>21</td>
                                <td>4</td>
			</tr>
			<tr>
				<td>FoL17</td>
				<td>ekoauto</td>
				<td>19:37:58</td>
				<td>18:48:16</td>
								<td>8</td>
				<td>8</td>
                                <td>2</td>
			</tr>
			<tr class="even">
				<td>FoL18</td>
				<td>houpací sud</td>
				<td>19:58:59</td>
				<td>18:39:43</td>
								<td>17</td>
				<td>1</td>
                                <td>1</td>
			</tr>
			<tr>
				<td>FoL19</td>
				<td>kapacitní tandem</td>
				<td>19:55:17</td>
				<td>18:24:08</td>
								<td>11</td>
				<td>3</td>
                                <td>1</td>
			</tr>
			<tr class="even">
				<td>FoL20</td>
				<td>heuréka</td>
				<td>19:57:44</td>
				<td>19:11:05</td>
								<td>10</td>
				<td>9</td>
                                <td>1</td>
			</tr>
			<tr>
				<td>FoL21</td>
				<td>ekologie nade vše</td>
				<td>19:40:15</td>
				<td>19:40:15</td>
								<td>1</td>
				<td>15</td>
                                <td>1</td>
			</tr>
			<tr class="even">
				<td>FoL22</td>
				<td>rezistorový blackbox</td>
				<td>19:31:28</td>
				<td>19:01:47</td>
								<td>2</td>
				<td>4</td>
                                <td>1</td>
			</tr>
			<tr>
				<td>FoL23</td>
				<td>oběžnice</td>
				<td></td>
				<td></td>
								<td>0</td>
				<td>13</td>
                                <td>1</td>
			</tr>
			<tr class="even">
				<td>FoL24</td>
				<td>rtuťotrysk</td>
				<td></td>
				<td></td>
								<td>0</td>
				<td>2</td>
                                <td>1</td>
			</tr>
			<tr>
				<td>FoL25</td>
				<td>bezrozměrný vodík</td>
				<td>19:47:15</td>
				<td>19:37:53</td>
								<td>3</td>
				<td>0</td>
                                <td>0</td>
			</tr>
			<tr class="even">
				<td>FoL26</td>
				<td>skákal pes</td>
				<td>19:54:26</td>
				<td>19:54:26</td>
								<td>1</td>
				<td>1</td>
                                <td>0</td>
			</tr>
			<tr>
				<td>FoL27</td>
				<td>P5</td>
				<td>19:50:35</td>
				<td>19:50:35</td>
								<td>1</td>
				<td>0</td>
                                <td>1</td>
			</tr>
			<tr class="even">
				<td>FoL28</td>
				<td>divná gravitace</td>
				<td></td>
				<td></td>
								<td>0</td>
				<td>2</td>
                                <td>0</td>
			</tr>
			<tr>
				<td>FoL29</td>
				<td>gram hexagramu</td>
				<td></td>
				<td></td>
								<td>0</td>
				<td>2</td>
                                <td>0</td>
			</tr>
			<tr class="even">
				<td>FoL30</td>
				<td>křišťálové akvárko</td>
				<td></td>
				<td></td>
								<td>0</td>
				<td>0</td>
                                <td>0</td>
			</tr>
			<tr>
				<td>M1</td>
				<td>besipka</td>
				<td>18:29:53</td>
				<td>18:04:52</td>
								<td>49</td>
				<td>80</td>
                                <td>0</td>
			</tr>
			<tr class="even">
				<td>M2</td>
				<td>koloukotě</td>
				<td>18:29:14</td>
				<td>18:11:20</td>
								<td>23</td>
				<td>13</td>
                                <td>0</td>
			</tr>
			<tr>
				<td>M3</td>
				<td>deprese na mostě</td>
				<td>18:29:25</td>
				<td>18:20:32</td>
								<td>7</td>
				<td>10</td>
                                <td>0</td>
			</tr>
			<tr class="even">
				<td>M4</td>
				<td>rozbitý výškoměr</td>
				<td></td>
				<td></td>
								<td>0</td>
				<td>3</td>
                                <td>0</td>
			</tr>
			<tr>
				<td>E1</td>
				<td>jiný laser</td>
				<td>18:28:49</td>
				<td>18:03:49</td>
								<td>31</td>
				<td>23</td>
                                <td>0</td>
			</tr>
			<tr class="even">
				<td>E2</td>
				<td>světluška</td>
				<td>18:27:58</td>
				<td>18:09:36</td>
								<td>8</td>
				<td>21</td>
                                <td>0</td>
			</tr>
			<tr>
				<td>E3</td>
				<td>vypněte to!</td>
				<td>18:29:54</td>
				<td>18:17:14</td>
								<td>3</td>
				<td>2</td>
                                <td>0</td>
			</tr>
			<tr class="even">
				<td>E4</td>
				<td>anulátor</td>
				<td></td>
				<td></td>
								<td>0</td>
				<td>0</td>
                                <td>0</td>
			</tr>
			<tr>
				<td>X1</td>
				<td>v metru</td>
				<td>18:27:20</td>
				<td>18:04:50</td>
								<td>8</td>
				<td>132</td>
                                <td>0</td>
			</tr>
			<tr class="even">
				<td>X2</td>
				<td>srážka</td>
				<td>18:26:58</td>
				<td>18:19:22</td>
								<td>3</td>
				<td>4</td>
                                <td>0</td>
			</tr>
			<tr>
				<td>X3</td>
				<td>blik</td>
				<td>18:29:47</td>
				<td>18:22:35</td>
								<td>2</td>
				<td>0</td>
                                <td>0</td>
			</tr>
			<tr class="even">
				<td>X4</td>
				<td>už to praská</td>
				<td>18:29:11</td>
				<td>18:29:11</td>
								<td>1</td>
				<td>0</td>
                                <td>0</td>
			</tr>
	</table>

{/block}
