{extends ../layout.phtml}
{block #bigcontent}
<p>Šedé jsou týmy, jež neprojevily během hry aktivitu.</p>
	<h2 id="hs_a">Středoškoláci A</h2>
	<table class="table table-condensed table-striped">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class=" ">
				<td>1</td>
				<td>m.raszyk</td>
				<td>
						88
				</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>2</td>
				<td>Gymji PRO Team 1337</td>
				<td>
						84
				</td>
				<td>
						4
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>3</td>
				<td>Spoza priehrady pri Istre</td>
				<td>
						64
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>4</td>
				<td>Gustiózny Jedácy Horalyek</td>
				<td>
						61
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>5</td>
				<td>Gymik</td>
				<td>
						59
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>6</td>
				<td>Budulínci</td>
				<td>
						53
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>7</td>
				<td>Gjarkovci</td>
				<td>
						50
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>8</td>
				<td>Borůvkový koláč s čučoriedkami</td>
				<td>
						45
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>9</td>
				<td>IQ v prášku</td>
				<td>
						34
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>10</td>
				<td>Jaroška</td>
				<td>
						28
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>11</td>
				<td>Ded moroz y snegurochky</td>
				<td>
						27
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>12</td>
				<td>Stěrači</td>
				<td>
						25
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>13</td>
				<td>Ozon</td>
				<td>
						20
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>14</td>
				<td>Vektor</td>
				<td>
						20
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class=" ">
				<td>15</td>
				<td>e^i*pi</td>
				<td>
						19
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>16</td>
				<td>Fyzika007</td>
				<td>
						19
				</td>
				<td>
						0
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class=" ">
				<td>17</td>
				<td>dašák 7,7</td>
				<td>
						18
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>18</td>
				<td>Gymuo</td>
				<td>
						18
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class=" ">
				<td>19</td>
				<td>Plachťáci</td>
				<td>
						17
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>20</td>
				<td>Mihule</td>
				<td>
						16
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>21</td>
				<td>GyMy</td>
				<td>
						13
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>22</td>
				<td>antiPoláci</td>
				<td>
						13
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class=" ">
				<td>23</td>
				<td>Motherfunctions</td>
				<td>
						12
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>24</td>
				<td>Absolutní nuly</td>
				<td>
						10
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class=" ">
				<td>25</td>
				<td>GymStr</td>
				<td>
						9
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>26</td>
				<td>!SVETLOM</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>27</td>
				<td>Alda tým</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
	</table>
	<h2 id="hs_b">Středoškoláci B</h2>
	<table class="table table-condensed table-striped">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class=" ">
				<td>1</td>
				<td>Qaterknan</td>
				<td>
						53
				</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>2</td>
				<td>GČL</td>
				<td>
						49
				</td>
				<td>
						5
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>3</td>
				<td>Hatalom</td>
				<td>
						34
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>4</td>
				<td>GJK 1</td>
				<td>
						33
				</td>
				<td>
						0
				</td>
				<td>
						6
				</td>
			</tr>
			<tr class=" ">
				<td>5</td>
				<td>Sprinteři 27</td>
				<td>
						32
				</td>
				<td>
						7
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>6</td>
				<td>Koalice flegmatických hadů</td>
				<td>
						31
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>7</td>
				<td>Černá síla</td>
				<td>
						30
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>8</td>
				<td>Tvoje Mama</td>
				<td>
						28
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class=" ">
				<td>9</td>
				<td>Gympláci1</td>
				<td>
						25
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>10</td>
				<td>Vytautas</td>
				<td>
						25
				</td>
				<td>
						0
				</td>
				<td>
						6
				</td>
			</tr>
			<tr class=" ">
				<td>11</td>
				<td>Abero</td>
				<td>
						23
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>12</td>
				<td>BUČETO</td>
				<td>
						21
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>13</td>
				<td>Nejbrutálnější drtiči</td>
				<td>
						18
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>14</td>
				<td>částice</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>15</td>
				<td>Wigym fyzici</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>16</td>
				<td>Neutrina</td>
				<td>
						12
				</td>
				<td>
						0
				</td>
				<td>
						5
				</td>
			</tr>
			<tr class=" ">
				<td>17</td>
				<td>Gymtri 4</td>
				<td>
						12
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>18</td>
				<td>GYMLOVO</td>
				<td>
						10
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>19</td>
				<td>MR.KRAB</td>
				<td>
						10
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>20</td>
				<td>Wigymos</td>
				<td>
						9
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>21</td>
				<td>Vítek</td>
				<td>
						9
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>22</td>
				<td>Jsme 0!</td>
				<td>
						9
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>23</td>
				<td>Le Vol</td>
				<td>
						9
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>24</td>
				<td>KuPeJoMi</td>
				<td>
						9
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>25</td>
				<td>IT crowd</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>26</td>
				<td>Gympláci2</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>27</td>
				<td>Páni Času</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>28</td>
				<td>Gymtri3</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class=" ">
				<td>29</td>
				<td>Loupáci</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>30</td>
				<td>Gymtri2</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>31</td>
				<td>GymHol</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
				<td>
						6
				</td>
			</tr>
			<tr class="even ">
				<td>32</td>
				<td>Limitováni k nekonečnu!</td>
				<td>
						5
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>33</td>
				<td>gymnázium, Český Krumlov</td>
				<td>
						5
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>34</td>
				<td>Bouráci</td>
				<td>
						4
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>35</td>
				<td>ČAG</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>36</td>
				<td>Štoláci</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>37</td>
				<td>ONI</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>38</td>
				<td>Jablíčkář</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>39</td>
				<td>Hamarik</td>
				<td>
						1
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>40</td>
				<td>GJKT</td>
				<td>
						1
				</td>
				<td>
						0
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class=" ">
				<td>41</td>
				<td>Brachtlova</td>
				<td>
						1
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>42</td>
				<td>Lyceáři</td>
				<td>
						-1
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" text-muted">
				<td>43</td>
				<td>eXtroZz</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>44</td>
				<td>Gympláci3</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>45</td>
				<td>Halaatchqowi bosoni</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>46</td>
				<td>YOLO</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
	</table>
	<h2 id="hs_c">Středoškoláci C</h2>
	<table class="table table-condensed table-striped">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class=" ">
				<td>1</td>
				<td>60letGymtri</td>
				<td>
						30
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>2</td>
				<td>Gratulujeme, jste 999999 návštěvník táto stránky !!!</td>
				<td>
						26
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>3</td>
				<td>Gymlovo Masters</td>
				<td>
						23
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>4</td>
				<td>Hodor</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>5</td>
				<td>Nový Jiřík</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>6</td>
				<td>Stechiometricke koeficienty</td>
				<td>
						13
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>7</td>
				<td>Wigumáci</td>
				<td>
						12
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>8</td>
				<td>JUNG_FLINTE</td>
				<td>
						12
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>9</td>
				<td>The Unexpectables</td>
				<td>
						11
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>10</td>
				<td>theEmpireStrikesBack</td>
				<td>
						10
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>11</td>
				<td>Klingoni</td>
				<td>
						10
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>12</td>
				<td>chemist.setBehaviour(crazy);</td>
				<td>
						9
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>13</td>
				<td>Pokus-omyl</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>14</td>
				<td>Hejčín 1</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>15</td>
				<td>Péťové</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>16</td>
				<td>NooBCakes</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>17</td>
				<td>SPONGEBOB</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>18</td>
				<td>Jasokyjba</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>19</td>
				<td>LeagueOfJustice</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>20</td>
				<td>Protoni</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>21</td>
				<td>KraHlupáci</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>22</td>
				<td>STARGATE</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>23</td>
				<td>CMYK</td>
				<td>
						5
				</td>
				<td>
						0
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class="even ">
				<td>24</td>
				<td>Planck</td>
				<td>
						5
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>25</td>
				<td>Nejnekvazidiagonalizovávatelnější</td>
				<td>
						5
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>26</td>
				<td>FAM</td>
				<td>
						4
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>27</td>
				<td>Jakub</td>
				<td>
						4
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>28</td>
				<td>Asociace Autonomních Alkoholiků</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>29</td>
				<td>superspiderninjasultravololosenseidogeilluminator3000</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class="even ">
				<td>30</td>
				<td>Mentalisti</td>
				<td>
						2
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>31</td>
				<td>Čepice</td>
				<td>
						1
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>32</td>
				<td>PastaFariani</td>
				<td>
						1
				</td>
				<td>
						0
				</td>
				<td>
						8
				</td>
			</tr>
			<tr class=" ">
				<td>33</td>
				<td>BKB</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>34</td>
				<td>Frikulíni</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>35</td>
				<td>Kolín X</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>36</td>
				<td>Koumácí</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>37</td>
				<td>ziky</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>38</td>
				<td>GéČKo</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class=" ">
				<td>39</td>
				<td>Samotář</td>
				<td>
						-2
				</td>
				<td>
						0
				</td>
				<td>
						5
				</td>
			</tr>
			<tr class="even text-muted">
				<td>40</td>
				<td>A-team</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>41</td>
				<td>BK-Brno</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>42</td>
				<td>Piškůtek</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>43</td>
				<td>Team -A</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>44</td>
				<td>Tl1</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
	</table>
	<h2 id="abroad">Zahraniční SŠ</h2>
	<table class="table table-condensed table-striped">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class=" ">
				<td>1</td>
				<td>Yognau(gh)ts</td>
				<td>
						63
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>2</td>
				<td>Bošnjaci</td>
				<td>
						50
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class=" ">
				<td>3</td>
				<td>breguenights</td>
				<td>
						43
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>4</td>
				<td>Magical 5</td>
				<td>
						37
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>5</td>
				<td>dindar</td>
				<td>
						27
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>6</td>
				<td>Radley College</td>
				<td>
						26
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class=" ">
				<td>7</td>
				<td>Ωmega</td>
				<td>
						18
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>8</td>
				<td>BiH-Zmajevi</td>
				<td>
						16
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>9</td>
				<td>BRoton</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>10</td>
				<td>Gaussian warriors</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>11</td>
				<td>Backstreet Boys</td>
				<td>
						12
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>12</td>
				<td>retapower</td>
				<td>
						11
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>13</td>
				<td>Los Suporters</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>14</td>
				<td>Sanerji9</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class=" ">
				<td>15</td>
				<td>NAVI</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class="even ">
				<td>16</td>
				<td>Pica of Galaxies</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class=" ">
				<td>17</td>
				<td>ISS2</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>18</td>
				<td>Pontes</td>
				<td>
						4
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>19</td>
				<td>Gauss</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>20</td>
				<td>ParaguayTeam</td>
				<td>
						2
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>21</td>
				<td>fisicopatas46</td>
				<td>
						2
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>22</td>
				<td>men in quarks</td>
				<td>
						2
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>23</td>
				<td>brazucas</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>24</td>
				<td>Fisicopatas</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>25</td>
				<td>corbotarik</td>
				<td>
						-6
				</td>
				<td>
						0
				</td>
				<td>
						13
				</td>
			</tr>
			<tr class="even ">
				<td>26</td>
				<td>Área 51</td>
				<td>
						-25
				</td>
				<td>
						0
				</td>
				<td>
						31
				</td>
			</tr>
			<tr class=" text-muted">
				<td>27</td>
				<td>Barbosa</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>28</td>
				<td>dadiani</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>29</td>
				<td>DetoNewtons</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>30</td>
				<td>FisicaCampinas</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>31</td>
				<td>HIAST</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>32</td>
				<td>HKteam</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>33</td>
				<td>Jojo</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>34</td>
				<td>Kilchy</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>35</td>
				<td>Lima&#039;s Physics</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>36</td>
				<td>Los desempleados</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>37</td>
				<td>Los Muchachos</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>38</td>
				<td>matherossi</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>39</td>
				<td>Matheus VCG</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>40</td>
				<td>Physics Online</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>41</td>
				<td>PhysicsPERJ</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>42</td>
				<td>Rafael Coracini</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>43</td>
				<td>Schrodinger</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>44</td>
				<td>Termomaníacs</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>45</td>
				<td>WINNER</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
	</table>
	<h2 id="open">Open</h2>
	<table class="table table-condensed table-striped">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class=" ">
				<td>1</td>
				<td>Veterani</td>
				<td>
						124
				</td>
				<td>
						26
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>2</td>
				<td>The Mathefficent Gaussketeers</td>
				<td>
						111
				</td>
				<td>
						13
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>3</td>
				<td>Smoluchowski&#039;s team</td>
				<td>
						108
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>4</td>
				<td>FtáKopySk</td>
				<td>
						100
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>5</td>
				<td>p5</td>
				<td>
						86
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>6</td>
				<td>proFO team</td>
				<td>
						77
				</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>7</td>
				<td>BobcatBKNUS</td>
				<td>
						71
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>8</td>
				<td>GU Kelvins</td>
				<td>
						68
				</td>
				<td>
						9
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>9</td>
				<td>Čučoriedie rozmanité</td>
				<td>
						67
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>10</td>
				<td>AAAAA</td>
				<td>
						66
				</td>
				<td>
						6
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class=" ">
				<td>11</td>
				<td>Hruskovica</td>
				<td>
						53
				</td>
				<td>
						0
				</td>
				<td>
						7
				</td>
			</tr>
			<tr class="even ">
				<td>12</td>
				<td>978-963-279-079-4</td>
				<td>
						50
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>13</td>
				<td>omama</td>
				<td>
						49
				</td>
				<td>
						0
				</td>
				<td>
						5
				</td>
			</tr>
			<tr class="even ">
				<td>14</td>
				<td>Principia</td>
				<td>
						39
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class=" ">
				<td>15</td>
				<td>BBBBB</td>
				<td>
						39
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class="even ">
				<td>16</td>
				<td>The Resistors</td>
				<td>
						35
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>17</td>
				<td>Tým týmů</td>
				<td>
						31
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>18</td>
				<td>Laser Cooling Group</td>
				<td>
						30
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>19</td>
				<td>Take the derivative!</td>
				<td>
						28
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>20</td>
				<td>The Stationary Action</td>
				<td>
						27
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>21</td>
				<td>Xenon</td>
				<td>
						25
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class="even ">
				<td>22</td>
				<td>Soustava jednotné díry</td>
				<td>
						22
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class=" ">
				<td>23</td>
				<td>Meneze&#039;s</td>
				<td>
						16
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="even ">
				<td>24</td>
				<td>TRINEC</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>25</td>
				<td>My Narcis I</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>26</td>
				<td>UNAL Bogotá</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" ">
				<td>27</td>
				<td>slimags</td>
				<td>
						13
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>28</td>
				<td>spdf</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class=" ">
				<td>29</td>
				<td>Red Dwarf</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="even ">
				<td>30</td>
				<td>Protons</td>
				<td>
						1
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class=" ">
				<td>31</td>
				<td>d(apocalypse)/dx=0</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even ">
				<td>32</td>
				<td>roja</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class=" text-muted">
				<td>33</td>
				<td>Amazonske anakondy</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>34</td>
				<td>Bender Rulez</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>35</td>
				<td>Flammenmeer</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>36</td>
				<td>Galileo</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>37</td>
				<td>Lefundes</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>38</td>
				<td>NEPAL</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>39</td>
				<td>Noshiro</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="even text-muted">
				<td>40</td>
				<td>Organizátoři</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class=" text-muted">
				<td>41</td>
				<td>Physic solvers</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
	</table>
