{extends ../layout.phtml}
{block #bigcontent}

<table class="table table-condensed table-striped">
		<thead>
			<th>#</th>
			<th>název</th>
			<th>nejhorší</th>
			<th>nejlepší</th>
						<th>správně</th>
			<th>špatně</th>
                        <th>přeskočeno</th>
		</thead>
			<tr class="" >
				<td>FoL1</td>
				<td>skákal pes</td>
				<td>19:51:17</td>
				<td>17:02:43</td>
				<td>149</td>
				<td>224</td>
                                <td>4</td>
			</tr>
			<tr class="even" >
				<td>FoL2</td>
				<td>zdroj záření</td>
				<td>19:59:49</td>
				<td>17:02:20</td>
				<td>105</td>
				<td>154</td>
                                <td>19</td>
			</tr>
			<tr class="" >
				<td>FoL3</td>
				<td>fluktuační</td>
				<td>19:56:06</td>
				<td>17:11:17</td>
				<td>76</td>
				<td>120</td>
                                <td>35</td>
			</tr>
			<tr class="even" >
				<td>FoL4</td>
				<td>ČEZ</td>
				<td>19:48:52</td>
				<td>17:03:58</td>
				<td>139</td>
				<td>181</td>
                                <td>4</td>
			</tr>
			<tr class=" text-muted" title="Zrušená úloha">
				<td>FoL5</td>
				<td>podzimní</td>
				<td></td>
				<td></td>
				<td>&mdash;</td>
				<td>&mdash;</td>
                                <td>16</td>
			</tr>
			<tr class="even text-muted" title="Zrušená úloha">
				<td>FoL6</td>
				<td>vláček motoráček</td>
				<td></td>
				<td></td>
				<td>&mdash;</td>
				<td>&mdash;</td>
                                <td>0</td>
			</tr>
			<tr class=" text-muted" title="Zrušená úloha">
				<td>FoL7</td>
				<td>srážka!!!</td>
				<td></td>
				<td></td>
				<td>&mdash;</td>
				<td>&mdash;</td>
                                <td>45</td>
			</tr>
			<tr class="even" >
				<td>FoL8</td>
				<td>půlkruhový analyzátor</td>
				<td>19:42:19</td>
				<td>17:13:04</td>
				<td>60</td>
				<td>41</td>
                                <td>37</td>
			</tr>
			<tr class="" >
				<td>FoL9</td>
				<td>upgrade</td>
				<td>19:59:46</td>
				<td>17:22:08</td>
				<td>58</td>
				<td>234</td>
                                <td>16</td>
			</tr>
			<tr class="even" >
				<td>FoL10</td>
				<td>nechť je tam rovnost</td>
				<td>19:59:16</td>
				<td>17:35:00</td>
				<td>45</td>
				<td>222</td>
                                <td>18</td>
			</tr>
			<tr class="" >
				<td>FoL11</td>
				<td>mošt</td>
				<td>19:58:39</td>
				<td>17:35:08</td>
				<td>43</td>
				<td>250</td>
                                <td>10</td>
			</tr>
			<tr class="even" >
				<td>FoL12</td>
				<td>Wienův filtr</td>
				<td>19:55:16</td>
				<td>17:32:00</td>
				<td>63</td>
				<td>9</td>
                                <td>9</td>
			</tr>
			<tr class="" >
				<td>FoL13</td>
				<td>pseudoledový čaj</td>
				<td>19:57:46</td>
				<td>17:39:12</td>
				<td>59</td>
				<td>108</td>
                                <td>7</td>
			</tr>
			<tr class="even" >
				<td>FoL14</td>
				<td>šplhoun aceton</td>
				<td>19:58:25</td>
				<td>17:48:00</td>
				<td>61</td>
				<td>76</td>
                                <td>4</td>
			</tr>
			<tr class="" >
				<td>FoL15</td>
				<td>kulatá</td>
				<td>19:59:57</td>
				<td>17:42:39</td>
				<td>42</td>
				<td>34</td>
                                <td>12</td>
			</tr>
			<tr class="even" >
				<td>FoL16</td>
				<td>žárovka a kondenzátor</td>
				<td>19:59:17</td>
				<td>18:00:54</td>
				<td>17</td>
				<td>77</td>
                                <td>9</td>
			</tr>
			<tr class="" >
				<td>FoL17</td>
				<td>tyčka na drátech</td>
				<td>19:53:33</td>
				<td>18:22:01</td>
				<td>14</td>
				<td>49</td>
                                <td>8</td>
			</tr>
			<tr class="even" >
				<td>FoL18</td>
				<td>totem</td>
				<td>19:55:40</td>
				<td>17:55:03</td>
				<td>33</td>
				<td>51</td>
                                <td>3</td>
			</tr>
			<tr class="" >
				<td>FoL19</td>
				<td>solární mánie</td>
				<td>19:59:10</td>
				<td>18:00:57</td>
				<td>31</td>
				<td>15</td>
                                <td>2</td>
			</tr>
			<tr class="even" >
				<td>FoL20</td>
				<td>rozpadovka</td>
				<td>19:57:42</td>
				<td>18:42:40</td>
				<td>19</td>
				<td>28</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL21</td>
				<td>tepelná koule</td>
				<td>19:56:43</td>
				<td>18:10:21</td>
				<td>26</td>
				<td>15</td>
                                <td>1</td>
			</tr>
			<tr class="even" >
				<td>FoL22</td>
				<td>analogový hustoměr</td>
				<td>19:59:51</td>
				<td>18:52:07</td>
				<td>8</td>
				<td>39</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL23</td>
				<td>natlakovaná krabička</td>
				<td>19:55:45</td>
				<td>18:21:17</td>
				<td>17</td>
				<td>24</td>
                                <td>1</td>
			</tr>
			<tr class="even" >
				<td>FoL24</td>
				<td>mistr světa ve skoku pro něco</td>
				<td>19:57:21</td>
				<td>18:40:15</td>
				<td>11</td>
				<td>36</td>
                                <td>2</td>
			</tr>
			<tr class="" >
				<td>FoL25</td>
				<td>kladky</td>
				<td>19:35:05</td>
				<td>19:22:04</td>
				<td>3</td>
				<td>41</td>
                                <td>2</td>
			</tr>
			<tr class="even" >
				<td>FoL26</td>
				<td>světlo v krabičce</td>
				<td>19:56:43</td>
				<td>19:05:17</td>
				<td>6</td>
				<td>20</td>
                                <td>2</td>
			</tr>
			<tr class="" >
				<td>FoL27</td>
				<td>osvícený vozík</td>
				<td>19:56:38</td>
				<td>19:05:28</td>
				<td>6</td>
				<td>7</td>
                                <td>1</td>
			</tr>
			<tr class="even" >
				<td>FoL28</td>
				<td>Zeměválec</td>
				<td>19:57:46</td>
				<td>19:11:24</td>
				<td>2</td>
				<td>4</td>
                                <td>2</td>
			</tr>
			<tr class="" >
				<td>FoL29</td>
				<td>hoď sem to kladivo</td>
				<td>19:57:08</td>
				<td>19:20:10</td>
				<td>4</td>
				<td>3</td>
                                <td>1</td>
			</tr>
			<tr class="even" >
				<td>FoL30</td>
				<td>bryndavá</td>
				<td>19:53:01</td>
				<td>19:53:01</td>
				<td>1</td>
				<td>2</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL31</td>
				<td>vážíme si rozpadů</td>
				<td>19:40:24</td>
				<td>19:40:24</td>
				<td>1</td>
				<td>1</td>
                                <td>1</td>
			</tr>
			<tr class="even" >
				<td>FoL32</td>
				<td>Flash</td>
				<td>19:36:57</td>
				<td>19:36:57</td>
				<td>1</td>
				<td>2</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL33</td>
				<td>we need to go deeper</td>
				<td></td>
				<td></td>
				<td>0</td>
				<td>1</td>
                                <td>1</td>
			</tr>
			<tr class="even" >
				<td>FoL34</td>
				<td>špejlička</td>
				<td>19:55:32</td>
				<td>19:55:32</td>
				<td>1</td>
				<td>0</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL35</td>
				<td>teserakt</td>
				<td></td>
				<td></td>
				<td>0</td>
				<td>1</td>
                                <td>1</td>
			</tr>
			<tr class="even" >
				<td>FoL36</td>
				<td>krátké ruce</td>
				<td></td>
				<td></td>
				<td>0</td>
				<td>0</td>
                                <td>1</td>
			</tr>
			<tr class="" >
				<td>FoL37</td>
				<td>odporný Fibonacci</td>
				<td></td>
				<td></td>
				<td>0</td>
				<td>1</td>
                                <td>0</td>
			</tr>
			<tr class="even" >
				<td>M1</td>
				<td>jehlové podpatky</td>
				<td>18:29:29</td>
				<td>18:03:28</td>
				<td>110</td>
				<td>154</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>M2</td>
				<td>zácpa</td>
				<td>18:29:57</td>
				<td>18:07:55</td>
				<td>21</td>
				<td>101</td>
                                <td>0</td>
			</tr>
			<tr class="even" >
				<td>M3</td>
				<td>velmi pomalá relativita</td>
				<td>18:28:59</td>
				<td>18:20:12</td>
				<td>5</td>
				<td>18</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>M4</td>
				<td>žbluňk</td>
				<td>18:22:29</td>
				<td>18:22:29</td>
				<td>1</td>
				<td>0</td>
                                <td>0</td>
			</tr>
			<tr class="even" >
				<td>E1</td>
				<td>blesk</td>
				<td>18:29:48</td>
				<td>18:06:21</td>
				<td>30</td>
				<td>89</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>E2</td>
				<td>zamotané odpory</td>
				<td>18:28:24</td>
				<td>18:08:40</td>
				<td>20</td>
				<td>4</td>
                                <td>0</td>
			</tr>
			<tr class="even" >
				<td>E3</td>
				<td>aberace</td>
				<td>18:29:52</td>
				<td>18:15:18</td>
				<td>5</td>
				<td>3</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>E4</td>
				<td>práce na nic</td>
				<td>18:29:20</td>
				<td>18:20:55</td>
				<td>3</td>
				<td>0</td>
                                <td>0</td>
			</tr>
			<tr class="even" >
				<td>X1</td>
				<td>roztáhneme se</td>
				<td>18:29:20</td>
				<td>18:07:30</td>
				<td>22</td>
				<td>191</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>X2</td>
				<td>topná sezóna</td>
				<td>18:29:55</td>
				<td>18:15:31</td>
				<td>6</td>
				<td>22</td>
                                <td>0</td>
			</tr>
			<tr class="even" >
				<td>X3</td>
				<td>šestiúhelníková koule</td>
				<td>18:27:51</td>
				<td>18:25:43</td>
				<td>2</td>
				<td>0</td>
                                <td>0</td>
			</tr>
			<tr class="" >
				<td>X4</td>
				<td>pevná či odpružená</td>
				<td></td>
				<td></td>
				<td>0</td>
				<td>0</td>
                                <td>0</td>
			</tr>
	</table>
