{extends ../layout.phtml}
{block #bigcontent}
<p>Šedé jsou týmy, jež neprojevily během hry aktivitu.</p>
	<h2 id="hs_a">Středoškoláci A</h2>
	<table class="table table-condensed table-striped small">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class="">
				<td>1</td>
				<td>Niesom si isty</td>
				<td>
						177
				</td>
				<td>
						9
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>2</td>
				<td>Qaterknan</td>
				<td>
						148
				</td>
				<td>
						18
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>3</td>
				<td>INCONTROVERTIBLE FLAMBOYANCE</td>
				<td>
						122
				</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>4</td>
				<td>The Devils</td>
				<td>
						105
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>5</td>
				<td>SG1</td>
				<td>
						101
				</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>6</td>
				<td>Ještě víc brutálnější drtiči</td>
				<td>
						100
				</td>
				<td>
						17
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>7</td>
				<td>Budulínci</td>
				<td>
						100
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="">
				<td>8</td>
				<td>Sprinteři 27</td>
				<td>
						97
				</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>9</td>
				<td>Hatalom</td>
				<td>
						95
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>10</td>
				<td>Ἐλεάται</td>
				<td>
						89
				</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>11</td>
				<td>Neutrina</td>
				<td>
						85
				</td>
				<td>
						4
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="">
				<td>12</td>
				<td>Gymcl</td>
				<td>
						84
				</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>13</td>
				<td>Ça va?</td>
				<td>
						76
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>14</td>
				<td>GJAK UB</td>
				<td>
						67
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>15</td>
				<td>Tým Josefa Balatky</td>
				<td>
						59
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>16</td>
				<td>Gymlovo A</td>
				<td>
						55
				</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>17</td>
				<td>Graciózny Výrobcovia Ovocia</td>
				<td>
						52
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>18</td>
				<td>FASA</td>
				<td>
						46
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>19</td>
				<td>Väljaheited</td>
				<td>
						44
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>20</td>
				<td>Scientia est potentia</td>
				<td>
						40
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>21</td>
				<td>Četa D</td>
				<td>
						39
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>22</td>
				<td>Perpetuálně Mobilní Skvadra</td>
				<td>
						39
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>23</td>
				<td>Los vidlákos</td>
				<td>
						38
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>24</td>
				<td>Pentakvark</td>
				<td>
						37
				</td>
				<td>
						5
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>25</td>
				<td>Ωμέγα</td>
				<td>
						32
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>26</td>
				<td>Veřejné bruslení</td>
				<td>
						25
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>27</td>
				<td>gjARMY</td>
				<td>
						24
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>28</td>
				<td>Démoni hou mlátičky gou</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>29</td>
				<td>Lucifer</td>
				<td>
						11
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>30</td>
				<td>Kuřátka</td>
				<td>
						11
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>31</td>
				<td>Růžoví poníci</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>32</td>
				<td>GOH Doktůrci</td>
				<td>
						4
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>33</td>
				<td>Go Go Power Rangers!</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="text-muted">
				<td>34</td>
				<td>Wigymos</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="text-muted">
				<td>35</td>
				<td>Prvočíselná rada</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="text-muted">
				<td>36</td>
				<td>Mě bere Kuba</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
	</table>
	<h2 id="hs_b">Středoškoláci B</h2>
	<table class="table table-condensed table-striped small">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class="">
				<td>1</td>
				<td>Grupa Jedla a Horaliek</td>
				<td>
						90
				</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>2</td>
				<td>Gymtri</td>
				<td>
						87
				</td>
				<td>
						5
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>3</td>
				<td>Dream team</td>
				<td>
						67
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>4</td>
				<td>Schrödinger&#039;s Pussies</td>
				<td>
						61
				</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>5</td>
				<td>vytautas</td>
				<td>
						58
				</td>
				<td>
						9
				</td>
				<td>
						7
				</td>
			</tr>
			<tr class="">
				<td>6</td>
				<td>Kratochvíle</td>
				<td>
						54
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>7</td>
				<td>Bramborový salát</td>
				<td>
						53
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>8</td>
				<td>Marťánci</td>
				<td>
						53
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="">
				<td>9</td>
				<td>Hurá!</td>
				<td>
						49
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>10</td>
				<td>0xG</td>
				<td>
						47
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>11</td>
				<td>Gymmost</td>
				<td>
						47
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>12</td>
				<td>Pokus-omyl</td>
				<td>
						47
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>13</td>
				<td>Binomické koeficienty</td>
				<td>
						46
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>14</td>
				<td>3,5 TEAM</td>
				<td>
						44
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>15</td>
				<td>CMYK</td>
				<td>
						43
				</td>
				<td>
						9
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>16</td>
				<td>Loupáci</td>
				<td>
						42
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>17</td>
				<td>JGN</td>
				<td>
						32
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>18</td>
				<td>Wigumáci</td>
				<td>
						32
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>19</td>
				<td>Menom tohto teamu</td>
				<td>
						32
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>20</td>
				<td>Bratrstvo koňohlavců</td>
				<td>
						30
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="">
				<td>21</td>
				<td>JGN 2</td>
				<td>
						27
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>22</td>
				<td>Kvadratura čtverce</td>
				<td>
						25
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="">
				<td>23</td>
				<td>Permutation=1</td>
				<td>
						23
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>24</td>
				<td>Klingoni</td>
				<td>
						22
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>25</td>
				<td>Stechiometrické koeficienty</td>
				<td>
						20
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class="">
				<td>26</td>
				<td>DreamTeam!</td>
				<td>
						19
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>27</td>
				<td>Putinove deti</td>
				<td>
						16
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>28</td>
				<td>Vítek</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>29</td>
				<td>GJJ</td>
				<td>
						12
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>30</td>
				<td>PSJG</td>
				<td>
						11
				</td>
				<td>
						0
				</td>
				<td>
						9
				</td>
			</tr>
			<tr class="">
				<td>31</td>
				<td>duhovky</td>
				<td>
						10
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>32</td>
				<td>My nie sme ackari</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>33</td>
				<td>Marták</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>34</td>
				<td>SGJO</td>
				<td>
						4
				</td>
				<td>
						0
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class="">
				<td>35</td>
				<td>chemist.setBehaviour(&quot;crazy&quot;);</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>36</td>
				<td>9Pf3q47W</td>
				<td>
						2
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
	</table>
	<h2 id="hs_c">Středoškoláci C</h2>
	<table class="table table-condensed table-striped small">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class="">
				<td>1</td>
				<td>Kepleráci</td>
				<td>
						149
				</td>
				<td>
						13
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>2</td>
				<td>Jdeme si zahrát</td>
				<td>
						58
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>3</td>
				<td>P ^ 2 * M ^ 3</td>
				<td>
						51
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>4</td>
				<td>Error 404. Team not found!</td>
				<td>
						46
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>5</td>
				<td>Gymhol</td>
				<td>
						42
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="">
				<td>6</td>
				<td>GKH-JO-ŠI</td>
				<td>
						35
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="">
				<td>7</td>
				<td>...hm</td>
				<td>
						35
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>8</td>
				<td>Null</td>
				<td>
						31
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>9</td>
				<td>Gympos Chrabromil</td>
				<td>
						28
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>10</td>
				<td>Mach(a)ři</td>
				<td>
						24
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class="">
				<td>11</td>
				<td>Protoni007</td>
				<td>
						24
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>12</td>
				<td>Gymploidi</td>
				<td>
						24
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>13</td>
				<td>fks-2014</td>
				<td>
						23
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>14</td>
				<td>kyselinky</td>
				<td>
						23
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>15</td>
				<td>Péťové</td>
				<td>
						23
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>16</td>
				<td>42</td>
				<td>
						22
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>17</td>
				<td>Švábíci</td>
				<td>
						21
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>18</td>
				<td>Aluminium</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="">
				<td>19</td>
				<td>(J)elita</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>20</td>
				<td>Nápověda</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>21</td>
				<td>Passy Riot</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>22</td>
				<td>LeagueOfJustice</td>
				<td>
						13
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>23</td>
				<td>Korejský kečup</td>
				<td>
						11
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class="">
				<td>24</td>
				<td>1.InfAckaGPH</td>
				<td>
						10
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>25</td>
				<td>Mickeyho klubík</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>26</td>
				<td>Atomíci</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>27</td>
				<td>Dedo Elektrikár</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
				<td>
						6
				</td>
			</tr>
			<tr class="">
				<td>28</td>
				<td>No name</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>29</td>
				<td>SibalovciGPH</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>30</td>
				<td>Team Kožich</td>
				<td>
						5
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>31</td>
				<td>SuperEfkaGPHDS</td>
				<td>
						4
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="">
				<td>32</td>
				<td>12345 - Frikulíni jsou zpět!</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>33</td>
				<td>cečkaris-1.C</td>
				<td>
						1
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>34</td>
				<td>Gymlovo Starter</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="text-muted">
				<td>35</td>
				<td>Chaos-theory</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="text-muted">
				<td>36</td>
				<td>Dogy</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="text-muted">
				<td>37</td>
				<td>Bratrstvo</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
	</table>
	<h2 id="abroad">Zahraniční SŠ</h2>
	<table class="table table-condensed table-striped small">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class="">
				<td>1</td>
				<td>The Resistors are Back</td>
				<td>
						118
				</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>2</td>
				<td>Bosna i Hercegovina</td>
				<td>
						110
				</td>
				<td>
						8
				</td>
				<td>
						6
				</td>
			</tr>
			<tr class="">
				<td>3</td>
				<td>QEGS Wakefield</td>
				<td>
						80
				</td>
				<td>
						8
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="">
				<td>4</td>
				<td>One Man Army</td>
				<td>
						72
				</td>
				<td>
						0
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class="">
				<td>5</td>
				<td>Atm do zé</td>
				<td>
						70
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="">
				<td>6</td>
				<td>Razbit dobitak</td>
				<td>
						67
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>7</td>
				<td>Mi malo naletili</td>
				<td>
						63
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="">
				<td>8</td>
				<td>saudies</td>
				<td>
						60
				</td>
				<td>
						8
				</td>
				<td>
						4
				</td>
			</tr>
			<tr class="">
				<td>9</td>
				<td>Radley College 61</td>
				<td>
						58
				</td>
				<td>
						9
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>10</td>
				<td>Zodiac</td>
				<td>
						54
				</td>
				<td>
						0
				</td>
				<td>
						6
				</td>
			</tr>
			<tr class="">
				<td>11</td>
				<td>strong name</td>
				<td>
						51
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>12</td>
				<td>Radley College 62</td>
				<td>
						48
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>13</td>
				<td>unresistant resistances</td>
				<td>
						43
				</td>
				<td>
						9
				</td>
				<td>
						11
				</td>
			</tr>
			<tr class="">
				<td>14</td>
				<td>m1itafb</td>
				<td>
						31
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>15</td>
				<td>Rijad Logo - &quot;Teorija Vremena&quot;</td>
				<td>
						23
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>16</td>
				<td>HU3BR</td>
				<td>
						22
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>17</td>
				<td>Lone Bolt</td>
				<td>
						22
				</td>
				<td>
						0
				</td>
				<td>
						9
				</td>
			</tr>
			<tr class="">
				<td>18</td>
				<td>čtvrthrst</td>
				<td>
						22
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>19</td>
				<td>pioneers</td>
				<td>
						21
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="">
				<td>20</td>
				<td>Quinteto Fantástico</td>
				<td>
						18
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>21</td>
				<td>Jonnie</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>22</td>
				<td>Ublehe</td>
				<td>
						12
				</td>
				<td>
						0
				</td>
				<td>
						2
				</td>
			</tr>
			<tr class="">
				<td>23</td>
				<td>sman1 sumbar</td>
				<td>
						12
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>24</td>
				<td>Brasil</td>
				<td>
						10
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>25</td>
				<td>Noray</td>
				<td>
						10
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>26</td>
				<td>O.L.E.</td>
				<td>
						8
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>27</td>
				<td>Urania</td>
				<td>
						5
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>28</td>
				<td>the physical</td>
				<td>
						4
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>29</td>
				<td>PSP</td>
				<td>
						4
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>30</td>
				<td>SMAN 1 SUMBAR</td>
				<td>
						3
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>31</td>
				<td>Physics Brasil</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>32</td>
				<td>pukanka</td>
				<td>
						-35
				</td>
				<td>
						0
				</td>
				<td>
						41
				</td>
			</tr>
			<tr class="text-muted">
				<td>33</td>
				<td>FaraBOSS</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="text-muted">
				<td>34</td>
				<td>one + two = me</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
	</table>
	<h2 id="open">Open</h2>
	<table class="table table-condensed table-striped small">
		<thead>
			<th>#</th>
			<th>tým</th>
			<th>celkem bodů</th>
			<th>bonusové body</th>
			<th>záporné body</th>
		</thead>
			<tr class="">
				<td>1</td>
				<td>Smoluchowski&#039;s team</td>
				<td>
						254
				</td>
				<td>
						33
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>2</td>
				<td>pySkoFtáK</td>
				<td>
						244
				</td>
				<td>
						9
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>3</td>
				<td>physics_spirit</td>
				<td>
						224
				</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>4</td>
				<td>SIMPAN</td>
				<td>
						216
				</td>
				<td>
						25
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>5</td>
				<td>omama</td>
				<td>
						205
				</td>
				<td>
						14
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>6</td>
				<td>LenJedenMathmo</td>
				<td>
						183
				</td>
				<td>
						16
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>7</td>
				<td>The Martians</td>
				<td>
						173
				</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>8</td>
				<td>Mistři Fyzikálních Fíglů</td>
				<td>
						171
				</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>9</td>
				<td>Banda tupých hláv</td>
				<td>
						144
				</td>
				<td>
						9
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>10</td>
				<td>Pemgineers</td>
				<td>
						143
				</td>
				<td>
						9
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>11</td>
				<td>QEFD</td>
				<td>
						138
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>12</td>
				<td>The Mathefficent Gaussketeers</td>
				<td>
						131
				</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>13</td>
				<td>Výběr z oveček</td>
				<td>
						123
				</td>
				<td>
						17
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>14</td>
				<td>Freisenberger</td>
				<td>
						118
				</td>
				<td>
						16
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>15</td>
				<td>Nepovím</td>
				<td>
						112
				</td>
				<td>
						7
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>16</td>
				<td>Klub přátel kladných konstant</td>
				<td>
						103
				</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>17</td>
				<td>Corpus Physicists</td>
				<td>
						86
				</td>
				<td>
						6
				</td>
				<td>
						3
				</td>
			</tr>
			<tr class="">
				<td>18</td>
				<td>Quantum Brazil</td>
				<td>
						82
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>19</td>
				<td>Team Natsci</td>
				<td>
						73
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>20</td>
				<td>Hlavy</td>
				<td>
						70
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>21</td>
				<td>CGI@uu</td>
				<td>
						62
				</td>
				<td>
						6
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>22</td>
				<td>Squirrel</td>
				<td>
						61
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>23</td>
				<td>Výkvět fakulty sociálních věd</td>
				<td>
						59
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>24</td>
				<td>The cake is a smooth manifold.</td>
				<td>
						56
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>25</td>
				<td>Podtatranskí junáci</td>
				<td>
						38
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>26</td>
				<td>none</td>
				<td>
						32
				</td>
				<td>
						0
				</td>
				<td>
						1
				</td>
			</tr>
			<tr class="">
				<td>27</td>
				<td>Flamingsword</td>
				<td>
						20
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>28</td>
				<td>the newmind</td>
				<td>
						19
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="">
				<td>29</td>
				<td>Sacred Swords</td>
				<td>
						15
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="text-muted">
				<td>30</td>
				<td>Organizátoři</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="text-muted">
				<td>31</td>
				<td>PhysiczRocksdaWorld</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="text-muted">
				<td>32</td>
				<td>RONI</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="text-muted">
				<td>33</td>
				<td>thinkers</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="text-muted">
				<td>34</td>
				<td>TheAbsoluteZero</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
			<tr class="text-muted">
				<td>35</td>
				<td>Higgs&#039; field</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
				<td>
						0
				</td>
			</tr>
	</table>
