{extends ../layout.phtml}

{block #content}
    <div id="submenu">
	<ul>
		<li>
			<a href="{plink Stats:default}" title="{_'Výsledky'}">{_'Výsledky'}</a>
			<ul>
                            {foreach $categories AS $category => $name}
                                <li><a href="{plink Stats:default}#{$category}" title="{$name}">{$name}</a></li>
                            {/foreach}
			</ul>
		</li>
		<li><a href="{plink Stats:detail}" title="{_'Podrobné výsledky'}">{_'Podrobné výsledky'}</a></li>
		<li><a href="{plink Stats:tasks}" title="{_'Statistiky úkolů'}">{_'Statistiky úkolů'}</a></li>
	</ul>
    </div>
    <div id="subcontent">
	{block #subcontent}
	{/block}
    </div>
{/block}